;; Generated by :claw at 2021-06-11T21:43:09.831312+03:00
(asdf:defsystem #:aw-filament-runtime-bindings
  :description "Bindings generated by aw-filament"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :claw-utils)
  :components
  ((:file "bindings/runtime/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/runtime/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))