;; Generated by :claw at 2021-01-17T14:47:09.469564+03:00
(asdf:defsystem #:claw-filament-runtime-bindings
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :claw-utils)
  :components
  ((:file "bindings/runtime/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/runtime/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))