/* Generated by :claw at 2023-04-30T13:16:20.767136Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "private/filament/BufferInterfaceBlock.h"
#include "matc/MaterialCompiler.h"
#include "matc/Config.h"
#include "AwMemIo.h"
#include "AwToolUtils.h"
#include "image/LinearImage.h"
#include "imageio/BasisEncoder.h"
#include "imageio/ImageDecoder.h"
#include "imageio/ImageEncoder.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_sizeof__ZN2aw8filament5tools5memio12MaterialDataC2EPvj() {
return sizeof(aw::filament::tools::memio::MaterialData);
}
}
}
}
}

namespace image {
__CLAW_API void __claw__ZN5image12BasisEncoder7BuilderC1EOS1_(image::BasisEncoder::Builder* __claw_this_, image::BasisEncoder::Builder* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:55:9
new (__claw_this_) image::BasisEncoder::Builder(std::move(*that));
}
}

namespace image {
__CLAW_API void __claw_cE3AE40NE40imageE40SE40ImageEncoder_claw_dtor(image::ImageEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:29:20
__claw_this_->~ImageEncoder();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void* __claw__ZN2aw8filament5tools5memio12MaterialData4dataEv(aw::filament::tools::memio::MaterialData* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:27:11
return (void*) __claw_this_->data();
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_sizeof__ZN2aw8filament5tools5memio13InMemoryInputC2EPKcS5_j() {
return sizeof(aw::filament::tools::memio::InMemoryInput);
}
}
}
}
}

namespace image {
__CLAW_API image::BasisEncoder* __claw__ZN5image12BasisEncoder7Builder5buildEv(image::BasisEncoder::Builder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:124:23
return (image::BasisEncoder*) __claw_this_->build();
}
}

namespace image {
__CLAW_API image::LinearImage* __claw__ZN5image11LinearImageaSERKS0_(image::LinearImage* __claw_this_, const image::LinearImage* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:58:18
return (image::LinearImage*) (&__claw_this_->operator=(*that));
}
}

namespace image {
__CLAW_API void __claw__ZN5image12ImageDecoder7DecoderD1Ev(image::ImageDecoder::Decoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:43:17
__claw_this_->~Decoder();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig19setReflectionTargetEN4matc6Config8MetadataE(aw::filament::tools::memio::InMemoryConfig* __claw_this_, enum matc::Config::Metadata reflectionTarget) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:130:10
__claw_this_->setReflectionTarget(reflectionTarget);
}
}
}
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof__ZN5image12BasisEncoder7BuilderC2Ejj() {
return alignof(image::BasisEncoder::Builder);
}
}

namespace image {
__CLAW_API uint32_t __claw__ZNK5image11LinearImage8getWidthEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:102:14
return __claw_this_->getWidth();
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof_imageWImageDecoder() {
return alignof(image::ImageDecoder);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace util {
__CLAW_API int __claw__ZN2aw8filament5tools4util10resizeFileEPKcm(const char* filename, unsigned long new_size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:10:5
return aw::filament::tools::util::resizeFile(filename, new_size);
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryOutputC1Ev(aw::filament::tools::memio::InMemoryOutput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:38:14
new (__claw_this_) aw::filament::tools::memio::InMemoryOutput();
}
}
}
}
}

namespace filament {
__CLAW_API unsigned long long __claw_alignof__ZN8filament20BufferInterfaceBlockC2Ev() {
return alignof(filament::BufferInterfaceBlock);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace util {
__CLAW_API image::LinearImage* __claw__ZN2aw8filament5tools4util11decodeImageEPhjN5image12ImageDecoder10ColorSpaceE(image::LinearImage* __claw_result_, uint8_t* data, size_t size, enum image::ImageDecoder::ColorSpace sourceSpace) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:12:20
new (__claw_result_) image::LinearImage(aw::filament::tools::util::decodeImage(data, size, sourceSpace));
return __claw_result_;
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof_matcWCompiler() {
return alignof(matc::Compiler);
}
}

namespace image {
__CLAW_API float* __claw__ZN5image11LinearImage11getPixelRefEjj(image::LinearImage* __claw_this_, uint32_t column, uint32_t row) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:81:12
return (float*) __claw_this_->getPixelRef(column, row);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_alignof__ZN2aw8filament5tools5memio12MaterialDataC2EPvj() {
return alignof(aw::filament::tools::memio::MaterialData);
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof_matcWConfigWInput() {
return alignof(matc::Config::Input);
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc16MaterialCompiler15checkParametersERKNS_6ConfigE(matc::MaterialCompiler* __claw_this_, const matc::Config* config) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:40:10
return __claw_this_->checkParameters(*config);
}
}

namespace filament {
__CLAW_API void __claw__ZN8filament20BufferInterfaceBlockC1Ev(filament::BufferInterfaceBlock* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:49:5
new (__claw_this_) filament::BufferInterfaceBlock();
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_sizeof_filamatWMaterialBuilderWParameter() {
return sizeof(filamat::MaterialBuilder::Parameter);
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc6Config6OutputD1Ev(matc::Config::Output* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:58:17
__claw_this_->~Output();
}
}

namespace utils {
__CLAW_API unsigned long long __claw_sizeof__ZN5utils6bitsetIjLj1EvEC2Ev() {
return sizeof(utils::bitset<unsigned int,1,void>);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API ssize_t __claw__ZN2aw8filament5tools5memio13InMemoryInput4openEv(aw::filament::tools::memio::InMemoryInput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:77:13
return __claw_this_->open();
}
}
}
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof__ZN5image12BasisEncoderC2EOS0_() {
return alignof(image::BasisEncoder);
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof_imageWImageEncoder() {
return alignof(image::ImageEncoder);
}
}

namespace matc {
__CLAW_API enum matc::Config::OutputFormat __claw__ZNK4matc6Config15getOutputFormatEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:86:18
return __claw_this_->getOutputFormat();
}
}

namespace image {
__CLAW_API image::LinearImage* __claw__ZN5image12ImageDecoder7Decoder6decodeEv(image::LinearImage* __claw_result_, image::ImageDecoder::Decoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:42:29
new (__claw_result_) image::LinearImage(__claw_this_->decode());
return __claw_result_;
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof_imageWImageDecoder() {
return sizeof(image::ImageDecoder);
}
}

namespace image {
__CLAW_API bool __claw__ZN5image12ImageEncoder7Encoder6encodeERKNS_11LinearImageE(image::ImageEncoder::Encoder* __claw_this_, const image::LinearImage* image) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:57:22
return __claw_this_->encode(*image);
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof_filamentWmathWdetailsWTVecComparisonOperators0TVec3WunsignedWint1() {
return alignof(filament::math::details::TVecComparisonOperators<TVec3,unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API bool __claw__ZNK4matc6Config12printShadersEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:110:10
return __claw_this_->printShaders();
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder8miplevelEjjRKNS_11LinearImageE(image::BasisEncoder::Builder* __claw_this_, size_t mipIndex, size_t layerIndex, const image::LinearImage* image) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:119:18
return (image::BasisEncoder::Builder*) (&__claw_this_->miplevel(mipIndex, layerIndex, *image));
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_alignof_filamatWMaterialBuilderBase() {
return alignof(filamat::MaterialBuilderBase);
}
}

namespace image {
__CLAW_API void __claw__ZN5image12ImageEncoder7EncoderD1Ev(image::ImageEncoder::Encoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:58:17
__claw_this_->~Encoder();
}
}

namespace matc {
__CLAW_API bool __claw__ZNK4matc6Config7isDebugEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:78:10
return __claw_this_->isDebug();
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof_imageWImageEncoderWEncoder() {
return sizeof(image::ImageEncoder::Encoder);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig15setPrintShadersEb(aw::filament::tools::memio::InMemoryConfig* __claw_this_, bool printShaders) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:122:10
__claw_this_->setPrintShaders(printShaders);
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig8setDebugEb(aw::filament::tools::memio::InMemoryConfig* __claw_this_, bool mDebug) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:114:10
__claw_this_->setDebug(mDebug);
}
}
}
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof__ZN5image11LinearImageC2Ejjj() {
return alignof(image::LinearImage);
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof_imageWImageDecoderWDecoder() {
return alignof(image::ImageDecoder::Decoder);
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder7normalsEb(image::BasisEncoder::Builder* __claw_this_, bool enabled) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:98:18
return (image::BasisEncoder::Builder*) (&__claw_this_->normals(enabled));
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilderC1Ev(filamat::MaterialBuilder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:202:5
new (__claw_this_) filamat::MaterialBuilder();
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc6Config5Input5closeEv(matc::Config::Input* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:71:22
return __claw_this_->close();
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof_matcWConfig() {
return alignof(matc::Config);
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof_filamentWmathWdetailsWTVecUnaryOperators0TVec3WunsignedWint1() {
return alignof(filament::math::details::TVecUnaryOperators<TVec3,unsigned int>);
}
}
}
}

namespace image {
__CLAW_API void __claw_cE3AE40NE40imageE40SE40ImageDecoder_claw_dtor(image::ImageDecoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:29:20
__claw_this_->~ImageDecoder();
}
}

namespace image {
__CLAW_API size_t __claw__ZNK5image12BasisEncoder16getKtx2ByteCountEv(image::BasisEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:150:12
return __claw_this_->getKtx2ByteCount();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof_filamentWmathWdetailsWTVecProductOperators0TVec3WunsignedWint1() {
return sizeof(filament::math::details::TVecProductOperators<TVec3,unsigned int>);
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_sizeof__ZN2aw8filament5tools5memio14InMemoryConfigC2EPKcS5_j() {
return sizeof(aw::filament::tools::memio::InMemoryConfig);
}
}
}
}
}

namespace matc {
__CLAW_API ssize_t __claw__ZN4matc6Config5Input4openEv(matc::Config::Input* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:69:25
return __claw_this_->open();
}
}

namespace matc {
__CLAW_API void __claw_cE3AE40NE40matcE40SE40MaterialCompiler_claw_dtor(matc::MaterialCompiler* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7
__claw_this_->~MaterialCompiler();
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_sizeof__ZN7filamat15MaterialBuilderC2Ev() {
return sizeof(filamat::MaterialBuilder);
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof_filamentWmathWdetailsWTVecAddOperators0TVec3WunsignedWint1() {
return sizeof(filament::math::details::TVecAddOperators<TVec3,unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API matc::Config::Output* __claw__ZNK4matc6Config9getOutputEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:64:21
return (matc::Config::Output*) __claw_this_->getOutput();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof__ZN8filament4math7details5TVec3IjEC2Ev() {
return alignof(filament::math::details::TVec3<unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof__ZN4matc16MaterialCompilerC2Ev() {
return alignof(matc::MaterialCompiler);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig16setVariantFilterEh(aw::filament::tools::memio::InMemoryConfig* __claw_this_, uint8_t variantFilter) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:146:10
__claw_this_->setVariantFilter(variantFilter);
}
}
}
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof__ZN5image12BasisEncoderC2EOS0_() {
return sizeof(image::BasisEncoder);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API const char* __claw__ZNK2aw8filament5tools5memio13InMemoryInput7getNameEv(aw::filament::tools::memio::InMemoryInput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:92:17
return (const char*) __claw_this_->getName();
}
}
}
}
}

namespace image {
__CLAW_API void __claw__ZN5image11LinearImageC1ERKS0_(image::LinearImage* __claw_this_, const image::LinearImage* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:57:5
new (__claw_this_) image::LinearImage(*that);
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof_imageWImageDecoderWDecoder() {
return sizeof(image::ImageDecoder::Decoder);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API bool __claw__ZN2aw8filament5tools5memio14InMemoryOutput5writeEPKhj(aw::filament::tools::memio::InMemoryOutput* __claw_this_, const uint8_t* data, size_t size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:47:10
return __claw_this_->write(data, size);
}
}
}
}
}

namespace image {
__CLAW_API const float* __claw__ZNK5image11LinearImage11getPixelRefEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:75:18
return (const float*) __claw_this_->getPixelRef();
}
}

namespace image {
__CLAW_API void __claw__ZN5image12ImageDecoder7Decoder13setColorSpaceENS0_10ColorSpaceE(image::ImageDecoder::Decoder* __claw_this_, enum image::ImageDecoder::ColorSpace colorSpace) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:49:14
__claw_this_->setColorSpace(colorSpace);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig12setTargetApiEN7filamat19MaterialBuilderBase9TargetApiE(aw::filament::tools::memio::InMemoryConfig* __claw_this_, matc::Config::TargetApi targetApi) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:142:10
__claw_this_->setTargetApi(targetApi);
}
}
}
}
}

namespace image {
__CLAW_API void __claw__ZN5image12BasisEncoderC1EOS0_(image::BasisEncoder* __claw_this_, image::BasisEncoder* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:133:5
new (__claw_this_) image::BasisEncoder(std::move(*that));
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfigC1EPKcS5_j(aw::filament::tools::memio::InMemoryConfig* __claw_this_, const char* name, const char* data, size_t size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:103:14
new (__claw_this_) aw::filament::tools::memio::InMemoryConfig(name, data, size);
}
}
}
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof_filamentWmathWdetailsWTVecComparisonOperators0TVec3WunsignedWint1() {
return sizeof(filament::math::details::TVecComparisonOperators<TVec3,unsigned int>);
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API bool __claw__ZNK2aw8filament5tools5memio14InMemoryConfig14isPrintShadersEv(aw::filament::tools::memio::InMemoryConfig* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:118:10
return __claw_this_->isPrintShaders();
}
}
}
}
}

namespace image {
__CLAW_API void __claw__ZN5image12BasisEncoder7BuilderC1Ejj(image::BasisEncoder::Builder* __claw_this_, size_t mipCount, size_t layerCount) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:52:9
new (__claw_this_) image::BasisEncoder::Builder(mipCount, layerCount);
}
}

namespace image {
__CLAW_API const uint8_t* __claw__ZNK5image12BasisEncoder11getKtx2DataEv(image::BasisEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:158:20
return (const uint8_t*) __claw_this_->getKtx2Data();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof_filamentWmathWdetailsWTVecFunctions0TVec3WunsignedWint1() {
return alignof(filament::math::details::TVecFunctions<TVec3,unsigned int>);
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio13InMemoryInputD1Ev(aw::filament::tools::memio::InMemoryInput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:75:13
__claw_this_->~InMemoryInput();
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof_matcWConfigWOutput() {
return alignof(matc::Config::Output);
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_sizeof_filamatWMaterialBuilderBase() {
return sizeof(filamat::MaterialBuilderBase);
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc6Config5InputD1Ev(matc::Config::Input* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:68:17
__claw_this_->~Input();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API bool __claw__ZN2aw8filament5tools5memio14InMemoryOutput5closeEv(aw::filament::tools::memio::InMemoryOutput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:60:10
return __claw_this_->close();
}
}
}
}
}

namespace image {
__CLAW_API uint32_t __claw__ZNK5image11LinearImage11getChannelsEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:104:14
return __claw_this_->getChannels();
}
}

namespace matc {
__CLAW_API matc::Config::TargetApi __claw__ZNK4matc6Config12getTargetApiEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:106:15
return __claw_this_->getTargetApi();
}
}

namespace matc {
__CLAW_API enum filament::backend::FeatureLevel __claw__ZNK4matc6Config15getFeatureLevelEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:130:37
return __claw_this_->getFeatureLevel();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API matc::Config::Input* __claw__ZNK2aw8filament5tools5memio14InMemoryConfig8getInputEv(aw::filament::tools::memio::InMemoryConfig* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:154:26
return (matc::Config::Input*) __claw_this_->getInput();
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj() {
return alignof(matc::MaterialLexeme);
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc16MaterialCompilerC1Ev(matc::MaterialCompiler* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:36:5
new (__claw_this_) matc::MaterialCompiler();
}
}

namespace image {
__CLAW_API unsigned long long __claw_alignof_imageWImageEncoderWEncoder() {
return alignof(image::ImageEncoder::Encoder);
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder18intermediateFormatENS0_18IntermediateFormatE(image::BasisEncoder::Builder* __claw_this_, enum image::BasisEncoder::IntermediateFormat format) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:83:18
return (image::BasisEncoder::Builder*) (&__claw_this_->intermediateFormat(format));
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig16setRawShaderModeEb(aw::filament::tools::memio::InMemoryConfig* __claw_this_, bool rawShaderMode) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:126:10
__claw_this_->setRawShaderMode(rawShaderMode);
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API bool __claw__ZN2aw8filament5tools5memio14InMemoryOutput4openEv(aw::filament::tools::memio::InMemoryOutput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:43:10
return __claw_this_->open();
}
}
}
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc6Config6Output5closeEv(matc::Config::Output* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:62:22
return __claw_this_->close();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_alignof__ZN2aw8filament5tools5memio14InMemoryOutputC2Ev() {
return alignof(aw::filament::tools::memio::InMemoryOutput);
}
}
}
}
}

namespace filament {
__CLAW_API void __claw__ZN8filament20BufferInterfaceBlockC1EOS0_(filament::BufferInterfaceBlock* __claw_this_, filament::BufferInterfaceBlock* rhs) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:54:5
new (__claw_this_) filament::BufferInterfaceBlock(std::move(*rhs));
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof_matcWConfigWOutput() {
return sizeof(matc::Config::Output);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio13InMemoryInputC1EPKcS5_j(aw::filament::tools::memio::InMemoryInput* __claw_this_, const char* name, const char* data, size_t size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:72:14
new (__claw_this_) aw::filament::tools::memio::InMemoryInput(name, data, size);
}
}
}
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc16MaterialCompiler3runERKNS_6ConfigE(matc::MaterialCompiler* __claw_this_, const matc::Config* config) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:38:10
return __claw_this_->run(*config);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig15setOutputFormatEN4matc6Config12OutputFormatE(aw::filament::tools::memio::InMemoryConfig* __claw_this_, enum matc::Config::OutputFormat outputFormat) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:138:10
__claw_this_->setOutputFormat(outputFormat);
}
}
}
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_alignof__ZN7filamat15MaterialBuilderC2Ev() {
return alignof(filamat::MaterialBuilder);
}
}

namespace image {
__CLAW_API bool __claw__ZN5image12BasisEncoder6encodeEv(image::BasisEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:143:10
return __claw_this_->encode();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof_filamentWmathWdetailsWTVecProductOperators0TVec3WunsignedWint1() {
return alignof(filament::math::details::TVecProductOperators<TVec3,unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc6Config6Output4openEv(matc::Config::Output* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:59:22
return __claw_this_->open();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API bool __claw__ZN2aw8filament5tools5memio13InMemoryInput5closeEv(aw::filament::tools::memio::InMemoryInput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:88:10
return __claw_this_->close();
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_alignof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj() {
return alignof(matc::Lexeme<matc::MaterialType>);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_alignof__ZN2aw8filament5tools5memio13InMemoryInputC2EPKcS5_j() {
return alignof(aw::filament::tools::memio::InMemoryInput);
}
}
}
}
}

namespace matc {
__CLAW_API bool __claw__ZNK4matc6Config13rawShaderModeEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:114:10
return __claw_this_->rawShaderMode();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfigD1Ev(aw::filament::tools::memio::InMemoryConfig* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:109:13
__claw_this_->~InMemoryConfig();
}
}
}
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof_filamentWmathWdetailsWTVecUnaryOperators0TVec3WunsignedWint1() {
return sizeof(filament::math::details::TVecUnaryOperators<TVec3,unsigned int>);
}
}
}
}

namespace image {
__CLAW_API void __claw_cE3AE40NE40imageE40SE40ImageDecoder_claw_ctor(image::ImageDecoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:29:20
new (__claw_this_) image::ImageDecoder();
}
}

namespace image {
__CLAW_API enum image::ImageDecoder::ColorSpace __claw__ZNK5image12ImageDecoder7Decoder13getColorSpaceEv(image::ImageDecoder::Decoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:45:20
return __claw_this_->getColorSpace();
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilder9ParameterC1Ev(struct filamat::MaterialBuilder::Parameter* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:614:9
new (__claw_this_) filamat::MaterialBuilder::Parameter();
}
}

namespace image {
__CLAW_API uint32_t __claw__ZNK5image11LinearImage9getHeightEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:103:14
return __claw_this_->getHeight();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio12MaterialDataD1Ev(aw::filament::tools::memio::MaterialData* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:19:13
__claw_this_->~MaterialData();
}
}
}
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SubpassTypeENS5_13SamplerFormatENS5_9PrecisionE(struct filamat::MaterialBuilder::Parameter* __claw_this_, const char* paramName, filamat::MaterialBuilder::SubpassType t, filamat::MaterialBuilder::SamplerFormat f, filamat::MaterialBuilder::ParameterPrecision p) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:625:9
new (__claw_this_) filamat::MaterialBuilder::Parameter(paramName, t, f, p);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryOutputD1Ev(aw::filament::tools::memio::InMemoryOutput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:41:13
__claw_this_->~InMemoryOutput();
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API aw::filament::tools::memio::MaterialData* __claw__ZN2aw8filament5tools5memio14InMemoryOutput12materialDataEv(aw::filament::tools::memio::InMemoryOutput* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:56:19
return (aw::filament::tools::memio::MaterialData*) __claw_this_->materialData();
}
}
}
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder5quietEb(image::BasisEncoder::Builder* __claw_this_, bool enabled) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:112:18
return (image::BasisEncoder::Builder*) (&__claw_this_->quiet(enabled));
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_alignof__ZN2aw8filament5tools5memio14InMemoryConfigC2EPKcS5_j() {
return alignof(aw::filament::tools::memio::InMemoryConfig);
}
}
}
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio12MaterialDataC1EPvj(aw::filament::tools::memio::MaterialData* __claw_this_, void* data, size_t size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:12:5
new (__claw_this_) aw::filament::tools::memio::MaterialData(data, size);
}
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof_matcWConfig() {
return sizeof(matc::Config);
}
}

namespace image {
__CLAW_API void __claw__ZN5image11LinearImageC1Ev(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:63:5
new (__claw_this_) image::LinearImage();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API void __claw__ZN2aw8filament5tools5memio14InMemoryConfig11setPlatformEN7filamat19MaterialBuilderBase8PlatformE(aw::filament::tools::memio::InMemoryConfig* __claw_this_, matc::Config::Platform platform) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:134:10
__claw_this_->setPlatform(platform);
}
}
}
}
}

namespace image {
__CLAW_API void __claw_cE3AE40NE40imageE40SE40ImageEncoder_claw_ctor(image::ImageEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:29:20
new (__claw_this_) image::ImageEncoder();
}
}

namespace image {
__CLAW_API float* __claw__ZN5image11LinearImage11getPixelRefEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:69:12
return (float*) __claw_this_->getPixelRef();
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7BuilderaSEOS1_(image::BasisEncoder::Builder* __claw_this_, image::BasisEncoder::Builder* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:56:18
return (image::BasisEncoder::Builder*) (&__claw_this_->operator=(std::move(*that)));
}
}

namespace image {
__CLAW_API void __claw__ZN5image11LinearImage5resetEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:105:10
__claw_this_->reset();
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder4jobsEj(image::BasisEncoder::Builder* __claw_this_, size_t count) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:105:18
return (image::BasisEncoder::Builder*) (&__claw_this_->jobs(count));
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11UniformTypeEjNS5_9PrecisionE(struct filamat::MaterialBuilder::Parameter* __claw_this_, const char* paramName, filamat::MaterialBuilder::UniformType t, size_t typeSize, filamat::MaterialBuilder::ParameterPrecision p) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:621:9
new (__claw_this_) filamat::MaterialBuilder::Parameter(paramName, t, typeSize, p);
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilderD1Ev(filamat::MaterialBuilder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:203:5
__claw_this_->~MaterialBuilder();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace util {
__CLAW_API size_t __claw__ZN2aw8filament5tools4util11encodeImageEPhjN5image12ImageEncoder6FormatEPNS4_11LinearImageE(uint8_t* data, size_t size, enum image::ImageEncoder::Format format, image::LinearImage* image) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:14:8
return aw::filament::tools::util::encodeImage(data, size, format, image);
}
}
}
}
}

namespace matc {
__CLAW_API matc::Config::Optimization __claw__ZNK4matc6Config20getOptimizationLevelEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:94:18
return __claw_this_->getOptimizationLevel();
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc8CompilerD1Ev(matc::Compiler* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:28:13
__claw_this_->~Compiler();
}
}

namespace matc {
__CLAW_API bool __claw__ZN4matc6Config6Output5writeEPKhj(matc::Config::Output* __claw_this_, const uint8_t* data, size_t size) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:60:22
return __claw_this_->write(data, size);
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc14MaterialLexemeC1ENS_12MaterialTypeEPKcS3_jj(matc::MaterialLexeme* __claw_this_, enum matc::MaterialType type, const char* start, const char* end, size_t line, size_t pos) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:32:5
new (__claw_this_) matc::MaterialLexeme(type, start, end, line, pos);
}
}

namespace image {
__CLAW_API bool __claw__ZNK5image11LinearImage7isValidEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:106:10
return __claw_this_->isValid();
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc6ConfigD1Ev(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:54:13
__claw_this_->~Config();
}
}

namespace utils {
__CLAW_API void __claw__ZN5utils6bitsetIjLj1EvEC1Ev(utils::bitset<unsigned int,1,void>* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/utils/include/utils/bitset.h:59:5
new (__claw_this_) utils::bitset<unsigned int,1,void>();
}
}

namespace matc {
__CLAW_API filament::UserVariantFilterMask __claw__ZNK4matc6Config16getVariantFilterEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:118:37
return __claw_this_->getVariantFilter();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof__ZN8filament4math7details5TVec3IjEC2Ev() {
return sizeof(filament::math::details::TVec3<unsigned int>);
}
}
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof_imageWImageEncoder() {
return sizeof(image::ImageEncoder);
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilderC1EOS0_(filamat::MaterialBuilder* __claw_this_, filamat::MaterialBuilder* rhs) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:208:5
new (__claw_this_) filamat::MaterialBuilder(std::move(*rhs));
}
}

namespace image {
__CLAW_API void __claw__ZN5image12BasisEncoder7BuilderD1Ev(image::BasisEncoder::Builder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:54:9
__claw_this_->~Builder();
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API unsigned long long __claw_sizeof__ZN2aw8filament5tools5memio14InMemoryOutputC2Ev() {
return sizeof(aw::filament::tools::memio::InMemoryOutput);
}
}
}
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder7cubemapEb(image::BasisEncoder::Builder* __claw_this_, bool enabled) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:76:18
return (image::BasisEncoder::Builder*) (&__claw_this_->cubemap(enabled));
}
}

namespace matc {
__CLAW_API matc::Config::Platform __claw__ZNK4matc6Config11getPlatformEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:82:14
return __claw_this_->getPlatform();
}
}

namespace matc {
__CLAW_API void __claw__ZN4matc6Config20setOptimizationLevelEN7filamat19MaterialBuilderBase12OptimizationE(matc::Config* __claw_this_, matc::Config::Optimization level) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:98:10
__claw_this_->setOptimizationLevel(level);
}
}

namespace image {
__CLAW_API bool __claw__ZNK5image11LinearImagecvbEv(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:64:5
return __claw_this_->operator bool();
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj() {
return sizeof(matc::Lexeme<matc::MaterialType>);
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder6linearEb(image::BasisEncoder::Builder* __claw_this_, bool enabled) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:69:18
return (image::BasisEncoder::Builder*) (&__claw_this_->linear(enabled));
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API matc::Config::Output* __claw__ZNK2aw8filament5tools5memio14InMemoryConfig9getOutputEv(aw::filament::tools::memio::InMemoryConfig* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:150:27
return (matc::Config::Output*) __claw_this_->getOutput();
}
}
}
}
}

namespace matc {
__CLAW_API void __claw_cE3AE40NE40matcE40SE40MaterialLexeme_claw_dtor(matc::MaterialLexeme* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7
__claw_this_->~MaterialLexeme();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_sizeof_filamentWmathWdetailsWTVecFunctions0TVec3WunsignedWint1() {
return sizeof(filament::math::details::TVecFunctions<TVec3,unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj() {
return sizeof(matc::MaterialLexeme);
}
}

namespace aw {
namespace filament {
namespace tools {
namespace memio {
__CLAW_API size_t __claw__ZN2aw8filament5tools5memio12MaterialData4sizeEv(aw::filament::tools::memio::MaterialData* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:23:12
return __claw_this_->size();
}
}
}
}
}

namespace filament {
__CLAW_API unsigned long long __claw_sizeof__ZN8filament20BufferInterfaceBlockC2Ev() {
return sizeof(filament::BufferInterfaceBlock);
}
}

namespace filament {
__CLAW_API void __claw__ZN8filament20BufferInterfaceBlockD1Ev(filament::BufferInterfaceBlock* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:57:5
__claw_this_->~BufferInterfaceBlock();
}
}

namespace image {
__CLAW_API const float* __claw__ZNK5image11LinearImage11getPixelRefEjj(image::LinearImage* __claw_this_, uint32_t column, uint32_t row) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:93:18
return (const float*) __claw_this_->getPixelRef(column, row);
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof__ZN4matc16MaterialCompilerC2Ev() {
return sizeof(matc::MaterialCompiler);
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof_matcWCompiler() {
return sizeof(matc::Compiler);
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof__ZN5image12BasisEncoder7BuilderC2Ejj() {
return sizeof(image::BasisEncoder::Builder);
}
}

namespace utils {
__CLAW_API unsigned long long __claw_alignof__ZN5utils6bitsetIjLj1EvEC2Ev() {
return alignof(utils::bitset<unsigned int,1,void>);
}
}

namespace image {
__CLAW_API void __claw__ZN5image11LinearImageC1Ejjj(image::LinearImage* __claw_this_, uint32_t width, uint32_t height, uint32_t channels) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:52:5
new (__claw_this_) image::LinearImage(width, height, channels);
}
}

namespace image {
__CLAW_API void __claw__ZN5image11LinearImageD1Ev(image::LinearImage* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:47:5
__claw_this_->~LinearImage();
}
}

namespace matc {
__CLAW_API matc::Config::Input* __claw__ZNK4matc6Config8getInputEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:74:20
return (matc::Config::Input*) __claw_this_->getInput();
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API unsigned long long __claw_alignof_filamentWmathWdetailsWTVecAddOperators0TVec3WunsignedWint1() {
return alignof(filament::math::details::TVecAddOperators<TVec3,unsigned int>);
}
}
}
}

namespace matc {
__CLAW_API enum matc::Config::Metadata __claw__ZNK4matc6Config19getReflectionTargetEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:102:14
return __claw_this_->getReflectionTarget();
}
}

namespace matc {
__CLAW_API unsigned long long __claw_sizeof_matcWConfigWInput() {
return sizeof(matc::Config::Input);
}
}

namespace filamat {
__CLAW_API void __claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SamplerTypeENS5_13SamplerFormatENS5_9PrecisionE(struct filamat::MaterialBuilder::Parameter* __claw_this_, const char* paramName, filamat::MaterialBuilder::SamplerType t, filamat::MaterialBuilder::SamplerFormat f, filamat::MaterialBuilder::ParameterPrecision p) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:617:9
new (__claw_this_) filamat::MaterialBuilder::Parameter(paramName, t, f, p);
}
}

namespace matc {
__CLAW_API const char* __claw__ZNK4matc6Config5Input7getNameEv(matc::Config::Input* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:72:29
return (const char*) __claw_this_->getName();
}
}

namespace matc {
__CLAW_API bool __claw__ZNK4matc6Config7isValidEv(matc::Config* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:90:10
return __claw_this_->isValid();
}
}

namespace image {
__CLAW_API image::BasisEncoder* __claw__ZN5image12BasisEncoderaSEOS0_(image::BasisEncoder* __claw_this_, image::BasisEncoder* that) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:134:19
return (image::BasisEncoder*) (&__claw_this_->operator=(std::move(*that)));
}
}

namespace image {
__CLAW_API image::BasisEncoder::Builder* __claw__ZN5image12BasisEncoder7Builder9grayscaleEb(image::BasisEncoder::Builder* __claw_this_, bool enabled) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:90:18
return (image::BasisEncoder::Builder*) (&__claw_this_->grayscale(enabled));
}
}

namespace image {
__CLAW_API unsigned long long __claw_sizeof__ZN5image11LinearImageC2Ejjj() {
return sizeof(image::LinearImage);
}
}

namespace filament {
namespace math {
namespace details {
__CLAW_API void __claw__ZN8filament4math7details5TVec3IjEC1Ev(filament::math::details::TVec3<unsigned int>* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/vec3.h:84:33
new (__claw_this_) filament::math::details::TVec3<unsigned int>();
}
}
}
}

namespace filamat {
__CLAW_API unsigned long long __claw_alignof_filamatWMaterialBuilderWParameter() {
return alignof(filamat::MaterialBuilder::Parameter);
}
}

namespace image {
__CLAW_API void __claw__ZN5image12BasisEncoderD1Ev(image::BasisEncoder* __claw_this_) {
// /home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:132:5
__claw_this_->~BasisEncoder();
}
}

#if defined(__cplusplus)
}
#endif
