;; Generated by :claw at 2021-10-06T19:47:49.615907Z
(uiop:define-package :%filament.util (:use))
(uiop:define-package :aw-filament-tools-bindings~pristine (:use :cl))
(common-lisp:in-package :aw-filament-tools-bindings~pristine)

(defparameter %filament.util::+fp-int-upward+ 0)

(defparameter %filament.util::+fp-int-downward+ 1)

(defparameter %filament.util::+fp-int-towardzero+ 2)

(defparameter %filament.util::+fp-int-tonearestfromzero+ 3)

(defparameter %filament.util::+fp-int-tonearest+ 4)

(defparameter %filament.util::+fp-nan+ 0)

(defparameter %filament.util::+fp-infinite+ 1)

(defparameter %filament.util::+fp-zero+ 2)

(defparameter %filament.util::+fp-subnormal+ 3)

(defparameter %filament.util::+fp-normal+ 4)

(defparameter %filament.util::+pthread-cancel-deferred+ 0)

(defparameter %filament.util::+pthread-cancel-asynchronous+ 1)

(defparameter %filament.util::+pthread-cancel-enable+ 0)

(defparameter %filament.util::+pthread-cancel-disable+ 1)

(defparameter %filament.util::+pthread-create-joinable+ 0)

(defparameter %filament.util::+pthread-create-detached+ 1)

(defparameter %filament.util::+pthread-inherit-sched+ 0)

(defparameter %filament.util::+pthread-explicit-sched+ 1)

(defparameter %filament.util::+pthread-mutex-stalled+ 0)

(defparameter %filament.util::+pthread-mutex-stalled-np+ 0)

(defparameter %filament.util::+pthread-mutex-robust+ 1)

(defparameter %filament.util::+pthread-mutex-robust-np+ 1)

(defparameter %filament.util::+pthread-mutex-timed-np+ 0)

(defparameter %filament.util::+pthread-mutex-recursive-np+ 1)

(defparameter %filament.util::+pthread-mutex-errorcheck-np+ 2)

(defparameter %filament.util::+pthread-mutex-adaptive-np+ 3)

(defparameter %filament.util::+pthread-mutex-normal+ 0)

(defparameter %filament.util::+pthread-mutex-recursive+ 1)

(defparameter %filament.util::+pthread-mutex-errorcheck+ 2)

(defparameter %filament.util::+pthread-mutex-default+ 0)

(defparameter %filament.util::+pthread-mutex-fast-np+ 0)

(defparameter %filament.util::+pthread-prio-none+ 0)

(defparameter %filament.util::+pthread-prio-inherit+ 1)

(defparameter %filament.util::+pthread-prio-protect+ 2)

(defparameter %filament.util::+pthread-process-private+ 0)

(defparameter %filament.util::+pthread-process-shared+ 1)

(defparameter %filament.util::+pthread-rwlock-prefer-reader-np+ 0)

(defparameter %filament.util::+pthread-rwlock-prefer-writer-np+ 1)

(defparameter %filament.util::+pthread-rwlock-prefer-writer-nonrecursive-np+ 2)

(defparameter %filament.util::+pthread-rwlock-default-np+ 0)

(defparameter %filament.util::+pthread-scope-system+ 0)

(defparameter %filament.util::+pthread-scope-process+ 1)

(defparameter %filament.util::+%i-supper+ 256)

(defparameter %filament.util::+%i-slower+ 512)

(defparameter %filament.util::+%i-salpha+ 1024)

(defparameter %filament.util::+%i-sdigit+ 2048)

(defparameter %filament.util::+%i-sxdigit+ 4096)

(defparameter %filament.util::+%i-sspace+ 8192)

(defparameter %filament.util::+%i-sprint+ 16384)

(defparameter %filament.util::+%i-sgraph+ 32768)

(defparameter %filament.util::+%i-sblank+ 1)

(defparameter %filament.util::+%i-scntrl+ 2)

(defparameter %filament.util::+%i-spunct+ 4)

(defparameter %filament.util::+%i-salnum+ 8)

(defparameter %filament.util::+%%i-swupper+ 0)

(defparameter %filament.util::+%%i-swlower+ 1)

(defparameter %filament.util::+%%i-swalpha+ 2)

(defparameter %filament.util::+%%i-swdigit+ 3)

(defparameter %filament.util::+%%i-swxdigit+ 4)

(defparameter %filament.util::+%%i-swspace+ 5)

(defparameter %filament.util::+%%i-swprint+ 6)

(defparameter %filament.util::+%%i-swgraph+ 7)

(defparameter %filament.util::+%%i-swblank+ 8)

(defparameter %filament.util::+%%i-swcntrl+ 9)

(defparameter %filament.util::+%%i-swpunct+ 10)

(defparameter %filament.util::+%%i-swalnum+ 11)

(defparameter %filament.util::+%i-swupper+ 16777216)

(defparameter %filament.util::+%i-swlower+ 33554432)

(defparameter %filament.util::+%i-swalpha+ 67108864)

(defparameter %filament.util::+%i-swdigit+ 134217728)

(defparameter %filament.util::+%i-swxdigit+ 268435456)

(defparameter %filament.util::+%i-swspace+ 536870912)

(defparameter %filament.util::+%i-swprint+ 1073741824)

(defparameter %filament.util::+%i-swgraph+ -2147483648)

(defparameter %filament.util::+%i-swblank+ 65536)

(defparameter %filament.util::+%i-swcntrl+ 131072)

(defparameter %filament.util::+%i-swpunct+ 262144)

(defparameter %filament.util::+%i-swalnum+ 524288)

(iffi:deficlass (%filament.util::claw+filament+in-memory-config
                 :size-reporter
                 "__claw_sizeof__ZN4claw8filament14InMemoryConfigC2EPKcS3_m"
                 :alignment-reporter
                 "__claw_alignof__ZN4claw8filament14InMemoryConfigC2EPKcS3_m"
                 :constructor
                 %filament.util::claw+filament+in-memory-config
                 :destructor
                 %filament.util::claw+filament+~in-memory-config)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:103:7")

(iffi:defitype %filament.util::size-t
               :unsigned-long
               "/usr/lib/clang/12.0.1/include/stddef.h:46:23")

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryConfigC1EPKcS3_m"
               %filament.util::claw+filament+in-memory-config)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:105:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-config))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:deficlass (%filament.util::matc+config+input :size-reporter
                 "__claw_sizeof_matcWConfigWInput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWInput" :destructor
                 %filament.util::matc+~input)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:61:11")

(iffi:defifun ("__claw__ZNK4claw8filament14InMemoryConfig8getInputEv"
               %filament.util::claw+filament+get-input :non-mutating
               t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+input)
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:120:26"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-config)))

(iffi:deficlass (%filament.util::matc+config+output :size-reporter
                 "__claw_sizeof_matcWConfigWOutput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWOutput" :destructor
                 %filament.util::matc+~output)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:51:11")

(iffi:defifun ("__claw__ZNK4claw8filament14InMemoryConfig9getOutputEv"
               %filament.util::claw+filament+get-output :non-mutating
               t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+output)
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:116:27"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-config)))

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryConfigD1Ev"
               %filament.util::claw+filament+~in-memory-config)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:111:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-config)))

(iffi:deficlass (%filament.util::claw+filament+in-memory-input
                 :size-reporter
                 "__claw_sizeof__ZN4claw8filament13InMemoryInputC2EPKcS3_m"
                 :alignment-reporter
                 "__claw_alignof__ZN4claw8filament13InMemoryInputC2EPKcS3_m"
                 :constructor
                 %filament.util::claw+filament+in-memory-input
                 :destructor
                 %filament.util::claw+filament+~in-memory-input)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:72:7")

(iffi:defifun ("__claw__ZN4claw8filament13InMemoryInputC1EPKcS3_m"
               %filament.util::claw+filament+in-memory-input)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:74:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-input))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN4claw8filament13InMemoryInput5closeEv"
               %filament.util::claw+filament+close)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:90:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-input)))

(iffi:defifun ("__claw__ZNK4claw8filament13InMemoryInput7getNameEv"
               %filament.util::claw+filament+get-name :non-mutating
               t)
              claw-utils:claw-string
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:94:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-input)))

(iffi:defitype %filament.util::ssize-t
               :int
               "/usr/include/sys/types.h:108:19")

(iffi:defifun ("__claw__ZN4claw8filament13InMemoryInput4openEv"
               %filament.util::claw+filament+open)
              %filament.util::ssize-t
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:79:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-input)))

(iffi:defifun ("__claw__ZN4claw8filament13InMemoryInputD1Ev"
               %filament.util::claw+filament+~in-memory-input)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:77:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-input)))

(iffi:deficlass (%filament.util::claw+filament+in-memory-output
                 :size-reporter
                 "__claw_sizeof__ZN4claw8filament14InMemoryOutputC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN4claw8filament14InMemoryOutputC2Ev"
                 :constructor
                 %filament.util::claw+filament+in-memory-output
                 :destructor
                 %filament.util::claw+filament+~in-memory-output)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:38:7")

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutputC1Ev"
               %filament.util::claw+filament+in-memory-output)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:40:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutput5closeEv"
               %filament.util::claw+filament+close)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:62:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output)))

(iffi:deficlass (%filament.util::claw+filament+material-data
                 :size-reporter
                 "__claw_sizeof__ZN4claw8filament12MaterialDataC2EPvm"
                 :alignment-reporter
                 "__claw_alignof__ZN4claw8filament12MaterialDataC2EPvm"
                 :constructor
                 %filament.util::claw+filament+material-data
                 :destructor
                 %filament.util::claw+filament+~material-data)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:12:7")

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutput12materialDataEv"
               %filament.util::claw+filament+material-data)
              (claw-utils:claw-pointer
               %filament.util::claw+filament+material-data)
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:58:19"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutput4openEv"
               %filament.util::claw+filament+open)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:45:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output)))

(iffi:defitype %filament.util::uint8-t
               :unsigned-char
               "/usr/include/bits/stdint-uintn.h:24:19")

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutput5writeEPKhm"
               %filament.util::claw+filament+write)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:49:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN4claw8filament14InMemoryOutputD1Ev"
               %filament.util::claw+filament+~in-memory-output)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:43:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN4claw8filament12MaterialDataC1EPvm"
               %filament.util::claw+filament+material-data)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:14:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+material-data))
              (%filament.util::data (claw-utils:claw-pointer :void))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN4claw8filament12MaterialData4dataEv"
               %filament.util::claw+filament+data)
              (claw-utils:claw-pointer :void)
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:29:11"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+material-data)))

(iffi:defifun ("__claw__ZN4claw8filament12MaterialData4sizeEv"
               %filament.util::claw+filament+size)
              %filament.util::size-t
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:25:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+material-data)))

(iffi:defifun ("__claw__ZN4claw8filament12MaterialDataD1Ev"
               %filament.util::claw+filament+~material-data)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/ClawMemIo.h:21:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::claw+filament+material-data)))

(iffi:deficlass (%filament.util::filamat+material-builder
                 :size-reporter
                 "__claw_sizeof__ZN7filamat15MaterialBuilderC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN7filamat15MaterialBuilderC2Ev"
                 :constructor
                 %filament.util::filamat+material-builder :destructor
                 %filament.util::filamat+~material-builder)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:177:20")

(cffi:defcenum (%filament.util::filamat+material-builder+output-target
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:213:16"
               (:color 0)
               (:depth 1))

(cffi:defcenum (%filament.util::filamat+material-builder+output-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:218:16"
               (:float 0)
               (:float2 1)
               (:float3 2)
               (:float4 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:182:16"
               (:custom0 0)
               (:custom1 1)
               (:custom2 2)
               (:custom3 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable-qualifier
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:209:16"
               (:out 0))

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilderC1Ev"
               %filament.util::filamat+material-builder)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:179:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(cffi:defcenum (%filament.util::backend+precision
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:226:12"
               (:low 0)
               (:medium 1)
               (:high 2)
               (:default 3))

(iffi:defitype %filament.util::filamat+material-builder+parameter-precision
               %filament.util::backend+precision
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:206:11")

(iffi:defistruct (%filament.util::filamat+material-builder+parameter
                  :size-reporter
                  "__claw_sizeof_filamatWMaterialBuilderWParameter"
                  :alignment-reporter
                  "__claw_alignof_filamatWMaterialBuilderWParameter"
                  :constructor %filament.util::filamat+parameter)
                 nil
                 "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:548:12")

(defparameter %filament.util::+invalid+ 0)

(defparameter %filament.util::+uniform+ 1)

(defparameter %filament.util::+sampler+ 2)

(defparameter %filament.util::+subpass+ 3)

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1Ev"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:549:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter)))

(cffi:defcenum (%filament.util::backend+sampler-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:234:12"
               (:2d 0)
               (:2d-array 1)
               (:cubemap 2)
               (:external 3)
               (:3d 4))

(iffi:defitype %filament.util::filamat+material-builder+sampler-type
               %filament.util::backend+sampler-type
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:203:11")

(cffi:defcenum (%filament.util::backend+sampler-format
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:248:12"
               (:int 0)
               (:uint 1)
               (:float 2)
               (:shadow 3))

(iffi:defitype %filament.util::filamat+material-builder+sampler-format
               %filament.util::backend+sampler-format
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:205:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SamplerTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:552:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+sampler-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+subpass-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:243:12"
               (:subpass-input 0))

(iffi:defitype %filament.util::filamat+material-builder+subpass-type
               %filament.util::backend+subpass-type
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:204:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SubpassTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:560:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+subpass-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+uniform-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:205:12"
               (:bool 0)
               (:bool2 1)
               (:bool3 2)
               (:bool4 3)
               (:float 4)
               (:float2 5)
               (:float3 6)
               (:float4 7)
               (:int 8)
               (:int2 9)
               (:int3 10)
               (:int4 11)
               (:uint 12)
               (:uint2 13)
               (:uint3 14)
               (:uint4 15)
               (:mat3 16)
               (:mat4 17))

(iffi:defitype %filament.util::filamat+material-builder+uniform-type
               %filament.util::backend+uniform-type
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:202:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11UniformTypeEmNS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:556:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+uniform-type)
              (%filament.util::type-size %filament.util::size-t)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(iffi:deficlass (%filament.util::filamat+material-builder-base
                 :size-reporter
                 "__claw_sizeof_filamatWMaterialBuilderBase"
                 :alignment-reporter
                 "__claw_alignof_filamatWMaterialBuilderBase")
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:51:20")

(cffi:defcenum (%filament.util::filamat+material-builder-base+platform
                :int)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:57:16"
               (:desktop 0)
               (:mobile 1)
               (:all 2))

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-api
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:63:16"
               (:opengl 1)
               (:vulkan 2)
               (:metal 4)
               (:all 7))

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-language
                :int)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:70:16"
               (:glsl 0)
               (:spirv 1))

(iffi:defifun ("__claw_cE3AE40NE40filamatE40SE40MaterialBuilder_claw_dtor"
               %filament.util::filamat+~material-builder)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:177:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(cffi:defcenum (%filament.util::matc+material-type :unsigned-int)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:24:6"
               (:block 0)
               (:identifier 1)
               (:unknown 2))

(iffi:deficlass (%filament.util::matc+compiler :size-reporter
                 "__claw_sizeof_matcWCompiler" :alignment-reporter
                 "__claw_alignof_matcWCompiler" :destructor
                 %filament.util::matc+~compiler)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:26:7")

(iffi:defifun ("__claw__ZN4matc8CompilerD1Ev"
               %filament.util::matc+~compiler)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:28:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+compiler)))

(iffi:deficlass (%filament.util::matc+config :size-reporter
                 "__claw_sizeof_matcWConfig" :alignment-reporter
                 "__claw_alignof_matcWConfig" :destructor
                 %filament.util::matc+~config)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:33:7")

(cffi:defcenum (%filament.util::matc+config+metadata :int)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:44:16"
               (:none 0)
               (:parameters 1))

(cffi:defcenum (%filament.util::matc+config+output-format :int)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:35:16"
               (:blob 0)
               (:c-header 1))

(iffi:defifun ("__claw__ZN4matc6ConfigD1Ev"
               %filament.util::matc+~config)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:49:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc6Config5InputD1Ev"
               %filament.util::matc+~input)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:63:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config6OutputD1Ev"
               %filament.util::matc+~output)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:53:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:deficlass (%filament.util::matc+jsonish-value :size-reporter
                 nil :alignment-reporter nil)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:33:7")

(iffi:deficlass (%filament.util::matc+lexeme<matc+material-type>
                 :size-reporter
                 "__claw_sizeof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_mm"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_mm")
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Lexeme.h:28:7")

(iffi:deficlass (%filament.util::matc+material-compiler
                 :size-reporter
                 "__claw_sizeof__ZN4matc16MaterialCompilerC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc16MaterialCompilerC2Ev"
                 :constructor %filament.util::matc+material-compiler
                 :destructor %filament.util::matc+~material-compiler)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7")

(iffi:defifun ("__claw__ZN4matc16MaterialCompilerC1Ev"
               %filament.util::matc+material-compiler)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:36:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler15checkParametersERKNS_6ConfigE"
               %filament.util::matc+check-parameters)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:40:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler3runERKNS_6ConfigE"
               %filament.util::matc+run)
              :bool
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:38:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:71:11")

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor-json
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:77:11")

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialCompiler_claw_dtor"
               %filament.util::matc+~material-compiler)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:deficlass (%filament.util::matc+material-lexeme :size-reporter
                 "__claw_sizeof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_mm"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_mm"
                 :constructor %filament.util::matc+material-lexeme
                 :destructor %filament.util::matc+~material-lexeme)
                nil
                "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7")

(iffi:defifun ("__claw__ZN4matc14MaterialLexemeC1ENS_12MaterialTypeEPKcS3_mm"
               %filament.util::matc+material-lexeme)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:32:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme))
              (%filament.util::type
               %filament.util::matc+material-type)
              (%filament.util::start claw-utils:claw-string)
              (%filament.util::end claw-utils:claw-string)
              (%filament.util::line %filament.util::size-t)
              (%filament.util::pos %filament.util::size-t))

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialLexeme_claw_dtor"
               %filament.util::matc+~material-lexeme)
              :void
              "/home/borodust/devel/repo/aw-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme)))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%filament.util::+pthread-prio-none+ :%filament.util)
  (export '%filament.util::+fp-subnormal+ :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-language
          :%filament.util)
  (export '%filament.util::filamat+parameter :%filament.util)
  (export '%filament.util::claw+filament+size :%filament.util)
  (export '%filament.util::+uniform+ :%filament.util)
  (export '%filament.util::+fp-normal+ :%filament.util)
  (export '%filament.util::+%%i-swgraph+ :%filament.util)
  (export '%filament.util::size-t :%filament.util)
  (export '%filament.util::+fp-int-downward+ :%filament.util)
  (export '%filament.util::+%i-swalpha+ :%filament.util)
  (export '%filament.util::+pthread-cancel-asynchronous+
          :%filament.util)
  (export '%filament.util::+%%i-swlower+ :%filament.util)
  (export '%filament.util::+fp-nan+ :%filament.util)
  (export '%filament.util::+%i-spunct+ :%filament.util)
  (export '%filament.util::+%i-swalnum+ :%filament.util)
  (export '%filament.util::+%%i-swpunct+ :%filament.util)
  (export '%filament.util::+fp-int-tonearest+ :%filament.util)
  (export '%filament.util::matc+config :%filament.util)
  (export '%filament.util::filamat+material-builder+subpass-type
          :%filament.util)
  (export '%filament.util::+%%i-swblank+ :%filament.util)
  (export '%filament.util::+%i-supper+ :%filament.util)
  (export '%filament.util::claw+filament+open :%filament.util)
  (export '%filament.util::claw+filament+get-output :%filament.util)
  (export '%filament.util::matc+material-type :%filament.util)
  (export '%filament.util::matc+config+output :%filament.util)
  (export '%filament.util::+pthread-prio-inherit+ :%filament.util)
  (export '%filament.util::+pthread-scope-system+ :%filament.util)
  (export '%filament.util::matc+~compiler :%filament.util)
  (export '%filament.util::matc+~config :%filament.util)
  (export '%filament.util::+fp-zero+ :%filament.util)
  (export '%filament.util::filamat+material-builder+uniform-type
          :%filament.util)
  (export '%filament.util::matc+lexeme<matc+material-type>
          :%filament.util)
  (export '%filament.util::+%i-salpha+ :%filament.util)
  (export '%filament.util::+%%i-swupper+ :%filament.util)
  (export '%filament.util::matc+~output :%filament.util)
  (export '%filament.util::filamat+material-builder+output-target
          :%filament.util)
  (export '%filament.util::matc+~material-lexeme :%filament.util)
  (export '%filament.util::matc+~material-compiler :%filament.util)
  (export '%filament.util::backend+uniform-type :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter
          :%filament.util)
  (export '%filament.util::+%%i-swprint+ :%filament.util)
  (export '%filament.util::+pthread-process-private+ :%filament.util)
  (export '%filament.util::filamat+material-builder-base
          :%filament.util)
  (export '%filament.util::matc+run :%filament.util)
  (export '%filament.util::filamat+material-builder+variable
          :%filament.util)
  (export '%filament.util::filamat+material-builder+output-type
          :%filament.util)
  (export '%filament.util::+%i-scntrl+ :%filament.util)
  (export '%filament.util::+%i-sspace+ :%filament.util)
  (export '%filament.util::+%i-swgraph+ :%filament.util)
  (export '%filament.util::+%i-swblank+ :%filament.util)
  (export '%filament.util::+pthread-mutex-robust-np+ :%filament.util)
  (export '%filament.util::+subpass+ :%filament.util)
  (export '%filament.util::+pthread-rwlock-prefer-reader-np+
          :%filament.util)
  (export '%filament.util::+%i-sgraph+ :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-api
          :%filament.util)
  (export '%filament.util::+pthread-mutex-recursive+ :%filament.util)
  (export '%filament.util::+%i-swspace+ :%filament.util)
  (export '%filament.util::+%i-sblank+ :%filament.util)
  (export '%filament.util::+pthread-mutex-fast-np+ :%filament.util)
  (export '%filament.util::+%%i-swdigit+ :%filament.util)
  (export '%filament.util::matc+jsonish-value :%filament.util)
  (export '%filament.util::+%i-swcntrl+ :%filament.util)
  (export '%filament.util::claw+filament+~in-memory-input
          :%filament.util)
  (export '%filament.util::+%i-swprint+ :%filament.util)
  (export '%filament.util::+%i-salnum+ :%filament.util)
  (export '%filament.util::+pthread-process-shared+ :%filament.util)
  (export '%filament.util::uint8-t :%filament.util)
  (export '%filament.util::+pthread-inherit-sched+ :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor-json
          :%filament.util)
  (export '%filament.util::matc+~input :%filament.util)
  (export '%filament.util::backend+subpass-type :%filament.util)
  (export '%filament.util::+pthread-create-joinable+ :%filament.util)
  (export '%filament.util::filamat+~material-builder :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter-precision
          :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-type
          :%filament.util)
  (export '%filament.util::filamat+material-builder-base+platform
          :%filament.util)
  (export '%filament.util::+pthread-mutex-timed-np+ :%filament.util)
  (export '%filament.util::+pthread-mutex-default+ :%filament.util)
  (export '%filament.util::+pthread-mutex-recursive-np+
          :%filament.util)
  (export '%filament.util::+%i-swdigit+ :%filament.util)
  (export '%filament.util::backend+precision :%filament.util)
  (export '%filament.util::matc+config+input :%filament.util)
  (export '%filament.util::+%%i-swxdigit+ :%filament.util)
  (export '%filament.util::+pthread-scope-process+ :%filament.util)
  (export '%filament.util::matc+material-lexeme :%filament.util)
  (export '%filament.util::filamat+material-builder :%filament.util)
  (export '%filament.util::+pthread-rwlock-prefer-writer-np+
          :%filament.util)
  (export '%filament.util::claw+filament+data :%filament.util)
  (export '%filament.util::matc+compiler :%filament.util)
  (export '%filament.util::+%i-swpunct+ :%filament.util)
  (export '%filament.util::+sampler+ :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-format
          :%filament.util)
  (export '%filament.util::+fp-infinite+ :%filament.util)
  (export '%filament.util::+pthread-mutex-robust+ :%filament.util)
  (export '%filament.util::claw+filament+in-memory-output
          :%filament.util)
  (export '%filament.util::claw+filament+in-memory-config
          :%filament.util)
  (export '%filament.util::+%i-sxdigit+ :%filament.util)
  (export '%filament.util::+%%i-swspace+ :%filament.util)
  (export '%filament.util::+pthread-mutex-stalled+ :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor
          :%filament.util)
  (export '%filament.util::+pthread-mutex-errorcheck+
          :%filament.util)
  (export '%filament.util::+pthread-rwlock-default-np+
          :%filament.util)
  (export '%filament.util::+invalid+ :%filament.util)
  (export '%filament.util::claw+filament+write :%filament.util)
  (export '%filament.util::claw+filament+get-name :%filament.util)
  (export '%filament.util::+%i-swupper+ :%filament.util)
  (export '%filament.util::+%i-sdigit+ :%filament.util)
  (export '%filament.util::claw+filament+~material-data
          :%filament.util)
  (export '%filament.util::+%i-slower+ :%filament.util)
  (export '%filament.util::+pthread-mutex-stalled-np+
          :%filament.util)
  (export '%filament.util::ssize-t :%filament.util)
  (export '%filament.util::+pthread-mutex-normal+ :%filament.util)
  (export '%filament.util::+fp-int-upward+ :%filament.util)
  (export '%filament.util::+fp-int-towardzero+ :%filament.util)
  (export '%filament.util::matc+check-parameters :%filament.util)
  (export '%filament.util::matc+config+output-format :%filament.util)
  (export '%filament.util::claw+filament+get-input :%filament.util)
  (export '%filament.util::matc+config+metadata :%filament.util)
  (export '%filament.util::+%i-swxdigit+ :%filament.util)
  (export '%filament.util::claw+filament+close :%filament.util)
  (export '%filament.util::+pthread-cancel-deferred+ :%filament.util)
  (export '%filament.util::+pthread-prio-protect+ :%filament.util)
  (export '%filament.util::claw+filament+~in-memory-output
          :%filament.util)
  (export '%filament.util::+pthread-explicit-sched+ :%filament.util)
  (export '%filament.util::+%i-sprint+ :%filament.util)
  (export '%filament.util::+fp-int-tonearestfromzero+
          :%filament.util)
  (export '%filament.util::matc+material-compiler :%filament.util)
  (export '%filament.util::+pthread-rwlock-prefer-writer-nonrecursive-np+
          :%filament.util)
  (export '%filament.util::+pthread-create-detached+ :%filament.util)
  (export '%filament.util::+%%i-swalnum+ :%filament.util)
  (export '%filament.util::+pthread-mutex-adaptive-np+
          :%filament.util)
  (export '%filament.util::backend+sampler-type :%filament.util)
  (export '%filament.util::claw+filament+~in-memory-config
          :%filament.util)
  (export '%filament.util::+pthread-mutex-errorcheck-np+
          :%filament.util)
  (export '%filament.util::+%%i-swalpha+ :%filament.util)
  (export '%filament.util::filamat+material-builder+variable-qualifier
          :%filament.util)
  (export '%filament.util::+pthread-cancel-enable+ :%filament.util)
  (export '%filament.util::claw+filament+material-data
          :%filament.util)
  (export '%filament.util::+%%i-swcntrl+ :%filament.util)
  (export '%filament.util::claw+filament+in-memory-input
          :%filament.util)
  (export '%filament.util::+%i-swlower+ :%filament.util)
  (export '%filament.util::backend+sampler-format :%filament.util)
  (export '%filament.util::+pthread-cancel-disable+ :%filament.util))

