;; Generated by :claw at 2023-04-30T13:16:25.508302Z
(uiop:define-package :%filament.util (:use))
(uiop:define-package :aw-filament-tools-bindings~pristine (:use :cl))
(common-lisp:in-package :aw-filament-tools-bindings~pristine)

(iffi:deficlass (%filament.util::aw+filament+tools+memio+in-memory-config
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament5tools5memio14InMemoryConfigC2EPKcS5_j"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament5tools5memio14InMemoryConfigC2EPKcS5_j"
                 :constructor
                 %filament.util::aw+filament+tools+memio+in-memory-config
                 :destructor
                 %filament.util::aw+filament+tools+memio+~in-memory-config)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:101:7")

(iffi:defitype %filament.util::size-t
               :unsigned-int
               "/usr/x86_64-w64-mingw32/include/corecrt.h:37:22")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfigC1EPKcS5_j"
               %filament.util::aw+filament+tools+memio+in-memory-config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:103:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:deficlass (%filament.util::matc+config+input :size-reporter
                 "__claw_sizeof_matcWConfigWInput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWInput" :destructor
                 %filament.util::matc+~input)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:66:11")

(iffi:defifun ("__claw__ZNK2aw8filament5tools5memio14InMemoryConfig8getInputEv"
               %filament.util::aw+filament+tools+memio+get-input
               :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+input)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:154:26"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config)))

(iffi:deficlass (%filament.util::matc+config+output :size-reporter
                 "__claw_sizeof_matcWConfigWOutput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWOutput" :destructor
                 %filament.util::matc+~output)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:56:11")

(iffi:defifun ("__claw__ZNK2aw8filament5tools5memio14InMemoryConfig9getOutputEv"
               %filament.util::aw+filament+tools+memio+get-output
               :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+output)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:150:27"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config)))

(iffi:defifun ("__claw__ZNK2aw8filament5tools5memio14InMemoryConfig14isPrintShadersEv"
               %filament.util::aw+filament+tools+memio+is-print-shaders
               :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:118:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig8setDebugEb"
               %filament.util::aw+filament+tools+memio+set-debug)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:114:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::m-debug :bool))

(cffi:defcenum (%filament.util::matc+config+output-format :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:35:16"
               (:blob 0)
               (:c-header 1))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig15setOutputFormatEN4matc6Config12OutputFormatE"
               %filament.util::aw+filament+tools+memio+set-output-format)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:138:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::output-format
               %filament.util::matc+config+output-format))

(cffi:defcenum (%filament.util::filamat+material-builder-base+platform
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:69:16"
               (:desktop 0)
               (:mobile 1)
               (:all 2))

(iffi:defitype %filament.util::matc+config+platform
               %filament.util::filamat+material-builder-base+platform
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:40:11")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig11setPlatformEN7filamat19MaterialBuilderBase8PlatformE"
               %filament.util::aw+filament+tools+memio+set-platform)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:134:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::platform
               %filament.util::matc+config+platform))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig15setPrintShadersEb"
               %filament.util::aw+filament+tools+memio+set-print-shaders)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:122:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::print-shaders :bool))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig16setRawShaderModeEb"
               %filament.util::aw+filament+tools+memio+set-raw-shader-mode)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:126:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::raw-shader-mode :bool))

(cffi:defcenum (%filament.util::matc+config+metadata :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:49:16"
               (:none 0)
               (:parameters 1))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig19setReflectionTargetEN4matc6Config8MetadataE"
               %filament.util::aw+filament+tools+memio+set-reflection-target)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:130:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::reflection-target
               %filament.util::matc+config+metadata))

(iffi:defitype %filament.util::uint8-t
               :unsigned-char
               "/usr/x86_64-w64-mingw32/include/stdint.h:36:25")

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-api
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:79:16"
               (:opengl 1)
               (:vulkan 2)
               (:metal 4)
               (:all 7))

(iffi:defitype %filament.util::matc+config+target-api
               %filament.util::filamat+material-builder-base+target-api
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:41:11")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig12setTargetApiEN7filamat19MaterialBuilderBase9TargetApiE"
               %filament.util::aw+filament+tools+memio+set-target-api)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:142:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::target-api
               %filament.util::matc+config+target-api))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfig16setVariantFilterEh"
               %filament.util::aw+filament+tools+memio+set-variant-filter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:146:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config))
              (%filament.util::variant-filter
               %filament.util::uint8-t))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryConfigD1Ev"
               %filament.util::aw+filament+tools+memio+~in-memory-config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:109:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-config)))

(iffi:deficlass (%filament.util::aw+filament+tools+memio+in-memory-input
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament5tools5memio13InMemoryInputC2EPKcS5_j"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament5tools5memio13InMemoryInputC2EPKcS5_j"
                 :constructor
                 %filament.util::aw+filament+tools+memio+in-memory-input
                 :destructor
                 %filament.util::aw+filament+tools+memio+~in-memory-input)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:70:7")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio13InMemoryInputC1EPKcS5_j"
               %filament.util::aw+filament+tools+memio+in-memory-input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:72:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-input))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio13InMemoryInput5closeEv"
               %filament.util::aw+filament+tools+memio+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:88:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-input)))

(iffi:defifun ("__claw__ZNK2aw8filament5tools5memio13InMemoryInput7getNameEv"
               %filament.util::aw+filament+tools+memio+get-name
               :non-mutating t)
              claw-utils:claw-string
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:92:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-input)))

(iffi:defitype %filament.util::ssize-t
               :int
               "/usr/x86_64-w64-mingw32/include/corecrt.h:47:13")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio13InMemoryInput4openEv"
               %filament.util::aw+filament+tools+memio+open)
              %filament.util::ssize-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:77:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-input)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio13InMemoryInputD1Ev"
               %filament.util::aw+filament+tools+memio+~in-memory-input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:75:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-input)))

(iffi:deficlass (%filament.util::aw+filament+tools+memio+in-memory-output
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament5tools5memio14InMemoryOutputC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament5tools5memio14InMemoryOutputC2Ev"
                 :constructor
                 %filament.util::aw+filament+tools+memio+in-memory-output
                 :destructor
                 %filament.util::aw+filament+tools+memio+~in-memory-output)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:36:7")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutputC1Ev"
               %filament.util::aw+filament+tools+memio+in-memory-output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:38:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutput5closeEv"
               %filament.util::aw+filament+tools+memio+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:60:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output)))

(iffi:deficlass (%filament.util::aw+filament+tools+memio+material-data
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament5tools5memio12MaterialDataC2EPvj"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament5tools5memio12MaterialDataC2EPvj"
                 :constructor
                 %filament.util::aw+filament+tools+memio+material-data
                 :destructor
                 %filament.util::aw+filament+tools+memio+~material-data)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:10:7")

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutput12materialDataEv"
               %filament.util::aw+filament+tools+memio+material-data)
              (claw-utils:claw-pointer
               %filament.util::aw+filament+tools+memio+material-data)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:56:19"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutput4openEv"
               %filament.util::aw+filament+tools+memio+open)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:43:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutput5writeEPKhj"
               %filament.util::aw+filament+tools+memio+write)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:47:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio14InMemoryOutputD1Ev"
               %filament.util::aw+filament+tools+memio+~in-memory-output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:41:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio12MaterialDataC1EPvj"
               %filament.util::aw+filament+tools+memio+material-data)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:12:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+material-data))
              (%filament.util::data (claw-utils:claw-pointer :void))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio12MaterialData4dataEv"
               %filament.util::aw+filament+tools+memio+data)
              (claw-utils:claw-pointer :void)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:27:11"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+material-data)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio12MaterialData4sizeEv"
               %filament.util::aw+filament+tools+memio+size)
              %filament.util::size-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:23:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+material-data)))

(iffi:defifun ("__claw__ZN2aw8filament5tools5memio12MaterialDataD1Ev"
               %filament.util::aw+filament+tools+memio+~material-data)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwMemIo.h:19:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+tools+memio+material-data)))

(iffi:deficlass (%filament.util::image+linear-image :size-reporter
                 "__claw_sizeof__ZN5image11LinearImageC2Ejjj"
                 :alignment-reporter
                 "__claw_alignof__ZN5image11LinearImageC2Ejjj"
                 :constructor %filament.util::image+linear-image
                 :destructor %filament.util::image+~linear-image)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:44:20")

(cffi:defcenum (%filament.util::image+image-decoder+color-space :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:31:16"
               (:linear 0)
               (:srgb 1))

(iffi:defifun ("__claw__ZN2aw8filament5tools4util11decodeImageEPhjN5image12ImageDecoder10ColorSpaceE"
               %filament.util::aw+filament+tools+util+decode-image)
              (claw-utils:claw-pointer
               %filament.util::image+linear-image)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:12:20"
              (%filament.util::%%claw-result-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t)
              (%filament.util::source-space
               %filament.util::image+image-decoder+color-space))

(cffi:defcenum (%filament.util::image+image-encoder+format :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:31:16"
               (:png 0)
               (:png-linear 1)
               (:hdr 2)
               (:rgbm 3)
               (:psd 4)
               (:exr 5)
               (:dds 6)
               (:dds-linear 7)
               (:rgb-10-11-11-rev 8))

(iffi:defifun ("__claw__ZN2aw8filament5tools4util11encodeImageEPhjN5image12ImageEncoder6FormatEPNS4_11LinearImageE"
               %filament.util::aw+filament+tools+util+encode-image)
              %filament.util::size-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:14:8"
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t)
              (%filament.util::format
               %filament.util::image+image-encoder+format)
              (%filament.util::image
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN2aw8filament5tools4util10resizeFileEPKcm"
               %filament.util::aw+filament+tools+util+resize-file)
              :int
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/adapter/tool-utils/AwToolUtils.h:10:5"
              (%filament.util::filename claw-utils:claw-string)
              (%filament.util::new-size :unsigned-long))

(iffi:deficlass (%filament.util::filamat+material-builder
                 :size-reporter
                 "__claw_sizeof__ZN7filamat15MaterialBuilderC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN7filamat15MaterialBuilderC2Ev"
                 :constructor
                 %filament.util::filamat+material-builder :destructor
                 %filament.util::filamat+~material-builder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:200:20")

(cffi:defcenum (%filament.util::filamat+material-builder+output-target
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:249:16"
               (:color 0)
               (:depth 1))

(cffi:defcenum (%filament.util::filamat+material-builder+output-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:254:16"
               (:float 0)
               (:float2 1)
               (:float3 2)
               (:float4 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:212:16"
               (:custom0 0)
               (:custom1 1)
               (:custom2 2)
               (:custom3 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable-qualifier
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:245:16"
               (:out 0))

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilderC1Ev"
               %filament.util::filamat+material-builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:202:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilderC1EOS0_"
               %filament.util::filamat+material-builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:208:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder))
              (%filament.util::rhs
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilderD1Ev"
               %filament.util::filamat+~material-builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:203:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(cffi:defcenum (%filament.util::backend+precision
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:291:12"
               (:low 0)
               (:medium 1)
               (:high 2)
               (:default 3))

(iffi:defitype %filament.util::filamat+material-builder+parameter-precision
               %filament.util::backend+precision
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:240:11")

(iffi:defistruct (%filament.util::filamat+material-builder+parameter
                  :size-reporter
                  "__claw_sizeof_filamatWMaterialBuilderWParameter"
                  :alignment-reporter
                  "__claw_alignof_filamatWMaterialBuilderWParameter"
                  :constructor %filament.util::filamat+parameter)
                 nil
                 "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:613:12")

(defparameter %filament.util::+invalid+ 0)

(defparameter %filament.util::+uniform+ 1)

(defparameter %filament.util::+sampler+ 2)

(defparameter %filament.util::+subpass+ 3)

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1Ev"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:614:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter)))

(cffi:defcenum (%filament.util::backend+sampler-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:299:12"
               (:2d 0)
               (:2d-array 1)
               (:cubemap 2)
               (:external 3)
               (:3d 4)
               (:cubemap-array 5))

(iffi:defitype %filament.util::filamat+material-builder+sampler-type
               %filament.util::backend+sampler-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:237:11")

(cffi:defcenum (%filament.util::backend+sampler-format
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:314:12"
               (:int 0)
               (:uint 1)
               (:float 2)
               (:shadow 3))

(iffi:defitype %filament.util::filamat+material-builder+sampler-format
               %filament.util::backend+sampler-format
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:239:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SamplerTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:617:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+sampler-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+subpass-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:309:12"
               (:subpass-input 0))

(iffi:defitype %filament.util::filamat+material-builder+subpass-type
               %filament.util::backend+subpass-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:238:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SubpassTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:625:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+subpass-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+uniform-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:260:12"
               (:bool 0)
               (:bool2 1)
               (:bool3 2)
               (:bool4 3)
               (:float 4)
               (:float2 5)
               (:float3 6)
               (:float4 7)
               (:int 8)
               (:int2 9)
               (:int3 10)
               (:int4 11)
               (:uint 12)
               (:uint2 13)
               (:uint3 14)
               (:uint4 15)
               (:mat3 16)
               (:mat4 17)
               (:struct 18))

(iffi:defitype %filament.util::filamat+material-builder+uniform-type
               %filament.util::backend+uniform-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:235:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11UniformTypeEjNS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:621:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+uniform-type)
              (%filament.util::type-size %filament.util::size-t)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(iffi:deficlass (%filament.util::filamat+material-builder-base
                 :size-reporter
                 "__claw_sizeof_filamatWMaterialBuilderBase"
                 :alignment-reporter
                 "__claw_alignof_filamatWMaterialBuilderBase")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:61:20")

(cffi:defcenum (%filament.util::filamat+material-builder-base+optimization
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:106:16"
               (:none 0)
               (:preprocessor 1)
               (:size 2)
               (:performance 3))

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-language
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:101:16"
               (:glsl 0)
               (:spirv 1))

(cffi:defcenum (%filament.util::backend+feature-level
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:108:12"
               (:|1| 1)
               (:|2| 2)
               (:|3| 3))

(iffi:deficlass (%filament.util::math+details+t-vec3<unsigned+int>
                 :size-reporter
                 "__claw_sizeof__ZN8filament4math7details5TVec3IjEC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN8filament4math7details5TVec3IjEC2Ev"
                 :constructor
                 %filament.util::math+details+t-vec3<unsigned+int>)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/vec3.h:33:24")

(iffi:defifun ("__claw__ZN8filament4math7details5TVec3IjEC1Ev"
               %filament.util::math+details+t-vec3<unsigned+int>)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/vec3.h:84:33"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::math+details+t-vec3<unsigned+int>)))

(iffi:deficlass (%filament.util::math+details+t-vec-add-operators<t-vec3+unsigned+int>
                 :size-reporter
                 "__claw_sizeof_filamentWmathWdetailsWTVecAddOperators0TVec3WunsignedWint1"
                 :alignment-reporter
                 "__claw_alignof_filamentWmathWdetailsWTVecAddOperators0TVec3WunsignedWint1")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/TVecHelpers.h:70:7")

(iffi:deficlass (%filament.util::math+details+t-vec-comparison-operators<t-vec3+unsigned+int>
                 :size-reporter
                 "__claw_sizeof_filamentWmathWdetailsWTVecComparisonOperators0TVec3WunsignedWint1"
                 :alignment-reporter
                 "__claw_alignof_filamentWmathWdetailsWTVecComparisonOperators0TVec3WunsignedWint1")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/TVecHelpers.h:268:7")

(iffi:deficlass (%filament.util::math+details+t-vec-functions<t-vec3+unsigned+int>
                 :size-reporter
                 "__claw_sizeof_filamentWmathWdetailsWTVecFunctions0TVec3WunsignedWint1"
                 :alignment-reporter
                 "__claw_alignof_filamentWmathWdetailsWTVecFunctions0TVec3WunsignedWint1")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/TVecHelpers.h:363:7")

(iffi:deficlass (%filament.util::math+details+t-vec-product-operators<t-vec3+unsigned+int>
                 :size-reporter
                 "__claw_sizeof_filamentWmathWdetailsWTVecProductOperators0TVec3WunsignedWint1"
                 :alignment-reporter
                 "__claw_alignof_filamentWmathWdetailsWTVecProductOperators0TVec3WunsignedWint1")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/TVecHelpers.h:154:7")

(iffi:deficlass (%filament.util::math+details+t-vec-unary-operators<t-vec3+unsigned+int>
                 :size-reporter
                 "__claw_sizeof_filamentWmathWdetailsWTVecUnaryOperators0TVec3WunsignedWint1"
                 :alignment-reporter
                 "__claw_alignof_filamentWmathWdetailsWTVecUnaryOperators0TVec3WunsignedWint1")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/math/include/math/TVecHelpers.h:247:7")

(iffi:deficlass (%filament.util::buffer-interface-block
                 :size-reporter
                 "__claw_sizeof__ZN8filament20BufferInterfaceBlockC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN8filament20BufferInterfaceBlockC2Ev"
                 :constructor %filament.util::buffer-interface-block
                 :destructor %filament.util::~buffer-interface-block)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:37:7")

(cffi:defcenum (%filament.util::buffer-interface-block+alignment
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:79:16"
               (:std140 0)
               (:std430 1))

(cffi:defbitfield (%filament.util::buffer-interface-block+qualifier
                   %filament.util::uint8-t)
                  "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:89:16"
                  (:coherent 1)
                  (:writeonly 2)
                  (:readonly 4)
                  (:volatile 8)
                  (:restrict 16))

(cffi:defcenum (%filament.util::buffer-interface-block+target
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:84:16"
               (:uniform 0)
               (:ssbo 1))

(iffi:defifun ("__claw__ZN8filament20BufferInterfaceBlockC1Ev"
               %filament.util::buffer-interface-block)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:49:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::buffer-interface-block)))

(iffi:defifun ("__claw__ZN8filament20BufferInterfaceBlockC1EOS0_"
               %filament.util::buffer-interface-block)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:54:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::buffer-interface-block))
              (%filament.util::rhs
               (claw-utils:claw-pointer
                %filament.util::buffer-interface-block)))

(iffi:defifun ("__claw__ZN8filament20BufferInterfaceBlockD1Ev"
               %filament.util::~buffer-interface-block)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/private/filament/BufferInterfaceBlock.h:57:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::buffer-interface-block)))

(iffi:defitype %filament.util::user-variant-filter-mask
               :unsigned-int
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/filament/MaterialEnums.h:245:7")

(iffi:deficlass (%filament.util::image+basis-encoder :size-reporter
                 "__claw_sizeof__ZN5image12BasisEncoderC2EOS0_"
                 :alignment-reporter
                 "__claw_alignof__ZN5image12BasisEncoderC2EOS0_"
                 :constructor %filament.util::image+basis-encoder
                 :destructor %filament.util::image+~basis-encoder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:31:20")

(cffi:defcenum (%filament.util::image+basis-encoder+intermediate-format
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:33:16"
               (:uastc 0)
               (:etc1s 1))

(iffi:defifun ("__claw__ZN5image12BasisEncoderC1EOS0_"
               %filament.util::image+basis-encoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:133:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoder6encodeEv"
               %filament.util::image+encode)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:143:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:defifun ("__claw__ZNK5image12BasisEncoder16getKtx2ByteCountEv"
               %filament.util::image+get-ktx2byte-count :non-mutating
               t)
              %filament.util::size-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:150:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:defifun ("__claw__ZNK5image12BasisEncoder11getKtx2DataEv"
               %filament.util::image+get-ktx2data :non-mutating t)
              (claw-utils:claw-pointer %filament.util::uint8-t)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:158:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoderaSEOS0_"
               %filament.util::image+operator=)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:134:19"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoderD1Ev"
               %filament.util::image+~basis-encoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:132:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder)))

(iffi:deficlass (%filament.util::image+basis-encoder+builder
                 :size-reporter
                 "__claw_sizeof__ZN5image12BasisEncoder7BuilderC2Ejj"
                 :alignment-reporter
                 "__claw_alignof__ZN5image12BasisEncoder7BuilderC2Ejj"
                 :constructor %filament.util::image+builder
                 :destructor %filament.util::image+~builder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:38:11")

(iffi:defifun ("__claw__ZN5image12BasisEncoder7BuilderC1EOS1_"
               %filament.util::image+builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:55:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7BuilderC1Ejj"
               %filament.util::image+builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:52:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::mip-count %filament.util::size-t)
              (%filament.util::layer-count %filament.util::size-t))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder5buildEv"
               %filament.util::image+build)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:124:23"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder7cubemapEb"
               %filament.util::image+cubemap)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:76:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::enabled :bool))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder9grayscaleEb"
               %filament.util::image+grayscale)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:90:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::enabled :bool))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder18intermediateFormatENS0_18IntermediateFormatE"
               %filament.util::image+intermediate-format)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:83:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::format
               %filament.util::image+basis-encoder+intermediate-format))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder4jobsEj"
               %filament.util::image+jobs)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:105:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::count %filament.util::size-t))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder6linearEb"
               %filament.util::image+linear)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:69:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::enabled :bool))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder8miplevelEjjRKNS_11LinearImageE"
               %filament.util::image+miplevel)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:119:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::mip-index %filament.util::size-t)
              (%filament.util::layer-index %filament.util::size-t)
              (%filament.util::image
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder7normalsEb"
               %filament.util::image+normals)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:98:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::enabled :bool))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7BuilderaSEOS1_"
               %filament.util::image+operator=)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:56:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder)))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7Builder5quietEb"
               %filament.util::image+quiet)
              (claw-utils:claw-pointer
               %filament.util::image+basis-encoder+builder)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:112:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder))
              (%filament.util::enabled :bool))

(iffi:defifun ("__claw__ZN5image12BasisEncoder7BuilderD1Ev"
               %filament.util::image+~builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:54:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+basis-encoder+builder)))

(iffi:defistruct (%filament.util::image+basis-encoder-builder-impl
                  :size-reporter nil :alignment-reporter nil)
                 nil
                 "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:28:8")

(iffi:defistruct (%filament.util::image+basis-encoder-impl
                  :size-reporter nil :alignment-reporter nil)
                 nil
                 "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/BasisEncoder.h:29:8")

(iffi:deficlass (%filament.util::image+image-decoder :size-reporter
                 "__claw_sizeof_imageWImageDecoder"
                 :alignment-reporter
                 "__claw_alignof_imageWImageDecoder" :constructor
                 %filament.util::image+image-decoder :destructor
                 %filament.util::image+~image-decoder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:29:20")

(cffi:defcenum (%filament.util::image+image-decoder+format :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:58:16"
               (:none 0)
               (:png 1)
               (:hdr 2)
               (:psd 3)
               (:exr 4))

(iffi:deficlass (%filament.util::image+image-decoder+decoder
                 :size-reporter
                 "__claw_sizeof_imageWImageDecoderWDecoder"
                 :alignment-reporter
                 "__claw_alignof_imageWImageDecoderWDecoder"
                 :destructor %filament.util::image+~decoder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:40:11")

(iffi:defifun ("__claw__ZN5image12ImageDecoder7Decoder6decodeEv"
               %filament.util::image+decode)
              (claw-utils:claw-pointer
               %filament.util::image+linear-image)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:42:29"
              (%filament.util::%%claw-result-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder+decoder)))

(iffi:defifun ("__claw__ZNK5image12ImageDecoder7Decoder13getColorSpaceEv"
               %filament.util::image+get-color-space :non-mutating t)
              %filament.util::image+image-decoder+color-space
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:45:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder+decoder)))

(iffi:defifun ("__claw__ZN5image12ImageDecoder7Decoder13setColorSpaceENS0_10ColorSpaceE"
               %filament.util::image+set-color-space)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:49:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder+decoder))
              (%filament.util::color-space
               %filament.util::image+image-decoder+color-space))

(iffi:defifun ("__claw__ZN5image12ImageDecoder7DecoderD1Ev"
               %filament.util::image+~decoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:43:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder+decoder)))

(iffi:defifun ("__claw_cE3AE40NE40imageE40SE40ImageDecoder_claw_ctor"
               %filament.util::image+image-decoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:29:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder)))

(iffi:defifun ("__claw_cE3AE40NE40imageE40SE40ImageDecoder_claw_dtor"
               %filament.util::image+~image-decoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageDecoder.h:29:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-decoder)))

(iffi:deficlass (%filament.util::image+image-encoder :size-reporter
                 "__claw_sizeof_imageWImageEncoder"
                 :alignment-reporter
                 "__claw_alignof_imageWImageEncoder" :constructor
                 %filament.util::image+image-encoder :destructor
                 %filament.util::image+~image-encoder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:29:20")

(iffi:deficlass (%filament.util::image+image-encoder+encoder
                 :size-reporter
                 "__claw_sizeof_imageWImageEncoderWEncoder"
                 :alignment-reporter
                 "__claw_alignof_imageWImageEncoderWEncoder"
                 :destructor %filament.util::image+~encoder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:55:11")

(iffi:defifun ("__claw__ZN5image12ImageEncoder7Encoder6encodeERKNS_11LinearImageE"
               %filament.util::image+encode)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:57:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-encoder+encoder))
              (%filament.util::image
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image12ImageEncoder7EncoderD1Ev"
               %filament.util::image+~encoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:58:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-encoder+encoder)))

(iffi:defifun ("__claw_cE3AE40NE40imageE40SE40ImageEncoder_claw_ctor"
               %filament.util::image+image-encoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:29:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-encoder)))

(iffi:defifun ("__claw_cE3AE40NE40imageE40SE40ImageEncoder_claw_dtor"
               %filament.util::image+~image-encoder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/imageio/include/imageio/ImageEncoder.h:29:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+image-encoder)))

(iffi:defifun ("__claw__ZN5image11LinearImageC1Ev"
               %filament.util::image+linear-image)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:63:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImageC1ERKS0_"
               %filament.util::image+linear-image)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:57:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defitype %filament.util::uint32-t
               :unsigned-int
               "/usr/x86_64-w64-mingw32/include/stdint.h:40:20")

(iffi:defifun ("__claw__ZN5image11LinearImageC1Ejjj"
               %filament.util::image+linear-image)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:52:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::width %filament.util::uint32-t)
              (%filament.util::height %filament.util::uint32-t)
              (%filament.util::channels %filament.util::uint32-t))

(iffi:defifun ("__claw__ZNK5image11LinearImage11getChannelsEv"
               %filament.util::image+get-channels :non-mutating t)
              %filament.util::uint32-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:104:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZNK5image11LinearImage9getHeightEv"
               %filament.util::image+get-height :non-mutating t)
              %filament.util::uint32-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:103:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImage11getPixelRefEv"
               %filament.util::image+get-pixel-ref)
              (claw-utils:claw-pointer :float)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:69:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZNK5image11LinearImage11getPixelRefEv"
               %filament.util::image+get-pixel-ref :non-mutating t)
              (claw-utils:claw-pointer :float)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:75:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImage11getPixelRefEjj"
               %filament.util::image+get-pixel-ref)
              (claw-utils:claw-pointer :float)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:81:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::column %filament.util::uint32-t)
              (%filament.util::row %filament.util::uint32-t))

(iffi:defifun ("__claw__ZNK5image11LinearImage11getPixelRefEjj"
               %filament.util::image+get-pixel-ref :non-mutating t)
              (claw-utils:claw-pointer :float)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:93:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::column %filament.util::uint32-t)
              (%filament.util::row %filament.util::uint32-t))

(iffi:defifun ("__claw__ZNK5image11LinearImage8getWidthEv"
               %filament.util::image+get-width :non-mutating t)
              %filament.util::uint32-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:102:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZNK5image11LinearImage7isValidEv"
               %filament.util::image+is-valid :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:106:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZNK5image11LinearImagecvbEv"
               %filament.util::image+operator+bool :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:64:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImageaSERKS0_"
               %filament.util::image+operator=)
              (claw-utils:claw-pointer
               %filament.util::image+linear-image)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:58:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image))
              (%filament.util::that
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImage5resetEv"
               %filament.util::image+reset)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:105:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(iffi:defifun ("__claw__ZN5image11LinearImageD1Ev"
               %filament.util::image+~linear-image)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/image/include/image/LinearImage.h:47:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::image+linear-image)))

(cffi:defcenum (%filament.util::matc+material-type :unsigned-int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:24:6"
               (:block 0)
               (:identifier 1)
               (:unknown 2))

(iffi:deficlass (%filament.util::matc+compiler :size-reporter
                 "__claw_sizeof_matcWCompiler" :alignment-reporter
                 "__claw_alignof_matcWCompiler" :destructor
                 %filament.util::matc+~compiler)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:26:7")

(iffi:defifun ("__claw__ZN4matc8CompilerD1Ev"
               %filament.util::matc+~compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:28:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+compiler)))

(iffi:deficlass (%filament.util::matc+config :size-reporter
                 "__claw_sizeof_matcWConfig" :alignment-reporter
                 "__claw_alignof_matcWConfig" :destructor
                 %filament.util::matc+~config)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:33:7")

(iffi:defifun ("__claw__ZNK4matc6Config15getFeatureLevelEv"
               %filament.util::matc+get-feature-level :non-mutating
               t)
              %filament.util::backend+feature-level
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:130:37"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config8getInputEv"
               %filament.util::matc+get-input :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+input)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:74:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defitype %filament.util::matc+config+optimization
               %filament.util::filamat+material-builder-base+optimization
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:42:11")

(iffi:defifun ("__claw__ZNK4matc6Config20getOptimizationLevelEv"
               %filament.util::matc+get-optimization-level
               :non-mutating t)
              %filament.util::matc+config+optimization
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:94:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config9getOutputEv"
               %filament.util::matc+get-output :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+output)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:64:21"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config15getOutputFormatEv"
               %filament.util::matc+get-output-format :non-mutating
               t)
              %filament.util::matc+config+output-format
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:86:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config11getPlatformEv"
               %filament.util::matc+get-platform :non-mutating t)
              %filament.util::matc+config+platform
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:82:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config19getReflectionTargetEv"
               %filament.util::matc+get-reflection-target
               :non-mutating t)
              %filament.util::matc+config+metadata
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:102:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config12getTargetApiEv"
               %filament.util::matc+get-target-api :non-mutating t)
              %filament.util::matc+config+target-api
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:106:15"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config16getVariantFilterEv"
               %filament.util::matc+get-variant-filter :non-mutating
               t)
              %filament.util::user-variant-filter-mask
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:118:37"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config7isDebugEv"
               %filament.util::matc+is-debug :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:78:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config7isValidEv"
               %filament.util::matc+is-valid :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:90:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config12printShadersEv"
               %filament.util::matc+print-shaders :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:110:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config13rawShaderModeEv"
               %filament.util::matc+raw-shader-mode :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:114:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc6Config20setOptimizationLevelEN7filamat19MaterialBuilderBase12OptimizationE"
               %filament.util::matc+set-optimization-level)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:98:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config))
              (%filament.util::level
               %filament.util::matc+config+optimization))

(iffi:defifun ("__claw__ZN4matc6ConfigD1Ev"
               %filament.util::matc+~config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:54:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc6Config5Input5closeEv"
               %filament.util::matc+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:71:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZNK4matc6Config5Input7getNameEv"
               %filament.util::matc+get-name :non-mutating t)
              claw-utils:claw-string
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:72:29"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config5Input4openEv"
               %filament.util::matc+open)
              %filament.util::ssize-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:69:25"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config5InputD1Ev"
               %filament.util::matc+~input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:68:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config6Output5closeEv"
               %filament.util::matc+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:62:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:defifun ("__claw__ZN4matc6Config6Output4openEv"
               %filament.util::matc+open)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:59:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:defifun ("__claw__ZN4matc6Config6Output5writeEPKhj"
               %filament.util::matc+write)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:60:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN4matc6Config6OutputD1Ev"
               %filament.util::matc+~output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:58:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:deficlass (%filament.util::matc+jsonish-value :size-reporter
                 nil :alignment-reporter nil)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:33:7")

(iffi:deficlass (%filament.util::matc+lexeme<matc+material-type>
                 :size-reporter
                 "__claw_sizeof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Lexeme.h:28:7")

(iffi:deficlass (%filament.util::matc+material-compiler
                 :size-reporter
                 "__claw_sizeof__ZN4matc16MaterialCompilerC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc16MaterialCompilerC2Ev"
                 :constructor %filament.util::matc+material-compiler
                 :destructor %filament.util::matc+~material-compiler)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7")

(iffi:defifun ("__claw__ZN4matc16MaterialCompilerC1Ev"
               %filament.util::matc+material-compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:36:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler15checkParametersERKNS_6ConfigE"
               %filament.util::matc+check-parameters)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:40:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler3runERKNS_6ConfigE"
               %filament.util::matc+run)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:38:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:75:11")

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor-json
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:81:11")

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialCompiler_claw_dtor"
               %filament.util::matc+~material-compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:deficlass (%filament.util::matc+material-lexeme :size-reporter
                 "__claw_sizeof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj"
                 :constructor %filament.util::matc+material-lexeme
                 :destructor %filament.util::matc+~material-lexeme)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7")

(iffi:defifun ("__claw__ZN4matc14MaterialLexemeC1ENS_12MaterialTypeEPKcS3_jj"
               %filament.util::matc+material-lexeme)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:32:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme))
              (%filament.util::type
               %filament.util::matc+material-type)
              (%filament.util::start claw-utils:claw-string)
              (%filament.util::end claw-utils:claw-string)
              (%filament.util::line %filament.util::size-t)
              (%filament.util::pos %filament.util::size-t))

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialLexeme_claw_dtor"
               %filament.util::matc+~material-lexeme)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme)))

(iffi:deficlass (%filament.util::utils+bitset<unsigned+int+1+void>
                 :size-reporter
                 "__claw_sizeof__ZN5utils6bitsetIjLj1EvEC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN5utils6bitsetIjLj1EvEC2Ev"
                 :constructor
                 %filament.util::utils+bitset<unsigned+int+1+void>)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/utils/include/utils/bitset.h:50:20")

(iffi:defifun ("__claw__ZN5utils6bitsetIjLj1EvEC1Ev"
               %filament.util::utils+bitset<unsigned+int+1+void>)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/utils/include/utils/bitset.h:59:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::utils+bitset<unsigned+int+1+void>)))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%filament.util::aw+filament+tools+memio+open
          :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-language
          :%filament.util)
  (export '%filament.util::uint32-t :%filament.util)
  (export '%filament.util::image+miplevel :%filament.util)
  (export '%filament.util::+uniform+ :%filament.util)
  (export '%filament.util::image+~image-encoder :%filament.util)
  (export '%filament.util::image+basis-encoder :%filament.util)
  (export '%filament.util::size-t :%filament.util)
  (export '%filament.util::matc+~material-lexeme :%filament.util)
  (export '%filament.util::image+grayscale :%filament.util)
  (export '%filament.util::image+get-height :%filament.util)
  (export '%filament.util::image+basis-encoder-impl :%filament.util)
  (export '%filament.util::filamat+material-builder+output-target
          :%filament.util)
  (export '%filament.util::matc+material-type :%filament.util)
  (export '%filament.util::matc+config+output :%filament.util)
  (export '%filament.util::matc+config+platform :%filament.util)
  (export '%filament.util::filamat+material-builder+uniform-type
          :%filament.util)
  (export '%filament.util::matc+set-optimization-level
          :%filament.util)
  (export '%filament.util::image+basis-encoder+builder
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-output-format
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-variant-filter
          :%filament.util)
  (export '%filament.util::matc+~compiler :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+~in-memory-output
          :%filament.util)
  (export '%filament.util::buffer-interface-block+alignment
          :%filament.util)
  (export '%filament.util::image+~encoder :%filament.util)
  (export '%filament.util::image+jobs :%filament.util)
  (export '%filament.util::matc+get-output-format :%filament.util)
  (export '%filament.util::filamat+material-builder+subpass-type
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+in-memory-output
          :%filament.util)
  (export '%filament.util::matc+get-output :%filament.util)
  (export '%filament.util::matc+~material-compiler :%filament.util)
  (export '%filament.util::image+get-color-space :%filament.util)
  (export '%filament.util::matc+lexeme<matc+material-type>
          :%filament.util)
  (export '%filament.util::image+image-decoder+decoder
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+~in-memory-input
          :%filament.util)
  (export '%filament.util::matc+raw-shader-mode :%filament.util)
  (export '%filament.util::image+quiet :%filament.util)
  (export '%filament.util::aw+filament+tools+util+decode-image
          :%filament.util)
  (export '%filament.util::backend+uniform-type :%filament.util)
  (export '%filament.util::filamat+material-builder-base
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-platform
          :%filament.util)
  (export '%filament.util::math+details+t-vec-add-operators<t-vec3+unsigned+int>
          :%filament.util)
  (export '%filament.util::filamat+material-builder+variable
          :%filament.util)
  (export '%filament.util::filamat+material-builder+output-type
          :%filament.util)
  (export '%filament.util::matc+run :%filament.util)
  (export '%filament.util::matc+jsonish-value :%filament.util)
  (export '%filament.util::math+details+t-vec-product-operators<t-vec3+unsigned+int>
          :%filament.util)
  (export '%filament.util::image+operator= :%filament.util)
  (export '%filament.util::matc+~config :%filament.util)
  (export '%filament.util::image+basis-encoder-builder-impl
          :%filament.util)
  (export '%filament.util::image+get-ktx2data :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+~material-data
          :%filament.util)
  (export '%filament.util::+subpass+ :%filament.util)
  (export '%filament.util::matc+get-name :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-api
          :%filament.util)
  (export '%filament.util::matc+~output :%filament.util)
  (export '%filament.util::buffer-interface-block :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+data
          :%filament.util)
  (export '%filament.util::matc+config+target-api :%filament.util)
  (export '%filament.util::uint8-t :%filament.util)
  (export '%filament.util::image+image-decoder :%filament.util)
  (export '%filament.util::matc+get-optimization-level
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+write
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+in-memory-input
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+close
          :%filament.util)
  (export '%filament.util::image+~basis-encoder :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-debug
          :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor-json
          :%filament.util)
  (export '%filament.util::matc+config :%filament.util)
  (export '%filament.util::matc+~input :%filament.util)
  (export '%filament.util::user-variant-filter-mask :%filament.util)
  (export '%filament.util::filamat+material-builder-base+platform
          :%filament.util)
  (export '%filament.util::filamat+~material-builder :%filament.util)
  (export '%filament.util::image+build :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+~in-memory-config
          :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter-precision
          :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-type
          :%filament.util)
  (export '%filament.util::image+cubemap :%filament.util)
  (export '%filament.util::image+get-width :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-raw-shader-mode
          :%filament.util)
  (export '%filament.util::image+basis-encoder+intermediate-format
          :%filament.util)
  (export '%filament.util::image+linear-image :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-target-api
          :%filament.util)
  (export '%filament.util::backend+precision :%filament.util)
  (export '%filament.util::matc+config+input :%filament.util)
  (export '%filament.util::backend+subpass-type :%filament.util)
  (export '%filament.util::image+get-ktx2byte-count :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+get-input
          :%filament.util)
  (export '%filament.util::image+decode :%filament.util)
  (export '%filament.util::matc+material-lexeme :%filament.util)
  (export '%filament.util::filamat+material-builder :%filament.util)
  (export '%filament.util::math+details+t-vec-comparison-operators<t-vec3+unsigned+int>
          :%filament.util)
  (export '%filament.util::image+reset :%filament.util)
  (export '%filament.util::image+normals :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+get-name
          :%filament.util)
  (export '%filament.util::image+image-decoder+format
          :%filament.util)
  (export '%filament.util::+sampler+ :%filament.util)
  (export '%filament.util::math+details+t-vec-unary-operators<t-vec3+unsigned+int>
          :%filament.util)
  (export '%filament.util::image+image-encoder+encoder
          :%filament.util)
  (export '%filament.util::image+encode :%filament.util)
  (export '%filament.util::matc+get-target-api :%filament.util)
  (export '%filament.util::image+image-decoder+color-space
          :%filament.util)
  (export '%filament.util::image+intermediate-format :%filament.util)
  (export '%filament.util::matc+get-variant-filter :%filament.util)
  (export '%filament.util::image+linear :%filament.util)
  (export '%filament.util::image+~linear-image :%filament.util)
  (export '%filament.util::matc+close :%filament.util)
  (export '%filament.util::aw+filament+tools+util+resize-file
          :%filament.util)
  (export '%filament.util::image+~decoder :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-format
          :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor
          :%filament.util)
  (export '%filament.util::matc+compiler :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+get-output
          :%filament.util)
  (export '%filament.util::+invalid+ :%filament.util)
  (export '%filament.util::image+operator+bool :%filament.util)
  (export '%filament.util::backend+feature-level :%filament.util)
  (export '%filament.util::image+get-channels :%filament.util)
  (export '%filament.util::matc+is-debug :%filament.util)
  (export '%filament.util::image+image-encoder :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-reflection-target
          :%filament.util)
  (export '%filament.util::utils+bitset<unsigned+int+1+void>
          :%filament.util)
  (export '%filament.util::image+~image-decoder :%filament.util)
  (export '%filament.util::image+set-color-space :%filament.util)
  (export '%filament.util::matc+is-valid :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+is-print-shaders
          :%filament.util)
  (export '%filament.util::buffer-interface-block+qualifier
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+in-memory-config
          :%filament.util)
  (export '%filament.util::~buffer-interface-block :%filament.util)
  (export '%filament.util::ssize-t :%filament.util)
  (export '%filament.util::matc+check-parameters :%filament.util)
  (export '%filament.util::filamat+material-builder-base+optimization
          :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+set-print-shaders
          :%filament.util)
  (export '%filament.util::matc+config+output-format :%filament.util)
  (export '%filament.util::matc+config+metadata :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+size
          :%filament.util)
  (export '%filament.util::matc+material-compiler :%filament.util)
  (export '%filament.util::aw+filament+tools+util+encode-image
          :%filament.util)
  (export '%filament.util::matc+config+optimization :%filament.util)
  (export '%filament.util::filamat+material-builder+variable-qualifier
          :%filament.util)
  (export '%filament.util::matc+get-input :%filament.util)
  (export '%filament.util::matc+open :%filament.util)
  (export '%filament.util::matc+get-reflection-target
          :%filament.util)
  (export '%filament.util::image+~builder :%filament.util)
  (export '%filament.util::matc+get-platform :%filament.util)
  (export '%filament.util::image+image-encoder+format
          :%filament.util)
  (export '%filament.util::matc+write :%filament.util)
  (export '%filament.util::backend+sampler-type :%filament.util)
  (export '%filament.util::aw+filament+tools+memio+material-data
          :%filament.util)
  (export '%filament.util::matc+get-feature-level :%filament.util)
  (export '%filament.util::image+get-pixel-ref :%filament.util)
  (export '%filament.util::filamat+parameter :%filament.util)
  (export '%filament.util::math+details+t-vec-functions<t-vec3+unsigned+int>
          :%filament.util)
  (export '%filament.util::buffer-interface-block+target
          :%filament.util)
  (export '%filament.util::image+builder :%filament.util)
  (export '%filament.util::matc+print-shaders :%filament.util)
  (export '%filament.util::backend+sampler-format :%filament.util)
  (export '%filament.util::math+details+t-vec3<unsigned+int>
          :%filament.util)
  (export '%filament.util::image+is-valid :%filament.util))

