;; Generated by :claw at 2022-08-28T21:16:56.714787Z
(uiop:define-package :%filament.util (:use))
(uiop:define-package :aw-filament-tools-bindings~pristine (:use :cl))
(common-lisp:in-package :aw-filament-tools-bindings~pristine)

(iffi:defifun ("__claw__ZN2aw8filament4util11resize_fileEPKcm"
               %filament.util::aw+filament+util+resize-file)
              :int
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawUtil.h:10:5"
              (%filament.util::filename claw-utils:claw-string)
              (%filament.util::new-size :unsigned-long))

(iffi:deficlass (%filament.util::aw+filament+in-memory-config
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament14InMemoryConfigC2EPKcS3_j"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament14InMemoryConfigC2EPKcS3_j"
                 :constructor
                 %filament.util::aw+filament+in-memory-config
                 :destructor
                 %filament.util::aw+filament+~in-memory-config)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:103:7")

(iffi:defitype %filament.util::size-t
               :unsigned-int
               "/usr/x86_64-w64-mingw32/include/corecrt.h:37:22")

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfigC1EPKcS3_j"
               %filament.util::aw+filament+in-memory-config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:105:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:deficlass (%filament.util::matc+config+input :size-reporter
                 "__claw_sizeof_matcWConfigWInput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWInput" :destructor
                 %filament.util::matc+~input)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:66:11")

(iffi:defifun ("__claw__ZNK2aw8filament14InMemoryConfig8getInputEv"
               %filament.util::aw+filament+get-input :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+input)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:156:26"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config)))

(iffi:deficlass (%filament.util::matc+config+output :size-reporter
                 "__claw_sizeof_matcWConfigWOutput"
                 :alignment-reporter
                 "__claw_alignof_matcWConfigWOutput" :destructor
                 %filament.util::matc+~output)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:56:11")

(iffi:defifun ("__claw__ZNK2aw8filament14InMemoryConfig9getOutputEv"
               %filament.util::aw+filament+get-output :non-mutating
               t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+output)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:152:27"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config)))

(iffi:defifun ("__claw__ZNK2aw8filament14InMemoryConfig14isPrintShadersEv"
               %filament.util::aw+filament+is-print-shaders
               :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:120:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config)))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig8setDebugEb"
               %filament.util::aw+filament+set-debug)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:116:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::m-debug :bool))

(cffi:defcenum (%filament.util::matc+config+output-format :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:35:16"
               (:blob 0)
               (:c-header 1))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig15setOutputFormatEN4matc6Config12OutputFormatE"
               %filament.util::aw+filament+set-output-format)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:140:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::output-format
               %filament.util::matc+config+output-format))

(cffi:defcenum (%filament.util::filamat+material-builder-base+platform
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:57:16"
               (:desktop 0)
               (:mobile 1)
               (:all 2))

(iffi:defitype %filament.util::matc+config+platform
               %filament.util::filamat+material-builder-base+platform
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:40:11")

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig11setPlatformEN7filamat19MaterialBuilderBase8PlatformE"
               %filament.util::aw+filament+set-platform)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:136:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::platform
               %filament.util::matc+config+platform))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig15setPrintShadersEb"
               %filament.util::aw+filament+set-print-shaders)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:124:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::print-shaders :bool))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig16setRawShaderModeEb"
               %filament.util::aw+filament+set-raw-shader-mode)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:128:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::raw-shader-mode :bool))

(cffi:defcenum (%filament.util::matc+config+metadata :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:49:16"
               (:none 0)
               (:parameters 1))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig19setReflectionTargetEN4matc6Config8MetadataE"
               %filament.util::aw+filament+set-reflection-target)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:132:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::reflection-target
               %filament.util::matc+config+metadata))

(iffi:defitype %filament.util::uint8-t
               :unsigned-char
               "/usr/x86_64-w64-mingw32/include/stdint.h:36:25")

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-api
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:63:16"
               (:opengl 1)
               (:vulkan 2)
               (:metal 4)
               (:all 7))

(iffi:defitype %filament.util::matc+config+target-api
               %filament.util::filamat+material-builder-base+target-api
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:41:11")

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig12setTargetApiEN7filamat19MaterialBuilderBase9TargetApiE"
               %filament.util::aw+filament+set-target-api)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:144:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::target-api
               %filament.util::matc+config+target-api))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfig16setVariantFilterEh"
               %filament.util::aw+filament+set-variant-filter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:148:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config))
              (%filament.util::variant-filter
               %filament.util::uint8-t))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryConfigD1Ev"
               %filament.util::aw+filament+~in-memory-config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:111:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-config)))

(iffi:deficlass (%filament.util::aw+filament+in-memory-input
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament13InMemoryInputC2EPKcS3_j"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament13InMemoryInputC2EPKcS3_j"
                 :constructor
                 %filament.util::aw+filament+in-memory-input
                 :destructor
                 %filament.util::aw+filament+~in-memory-input)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:72:7")

(iffi:defifun ("__claw__ZN2aw8filament13InMemoryInputC1EPKcS3_j"
               %filament.util::aw+filament+in-memory-input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:74:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-input))
              (%filament.util::name claw-utils:claw-string)
              (%filament.util::data claw-utils:claw-string)
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament13InMemoryInput5closeEv"
               %filament.util::aw+filament+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:90:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-input)))

(iffi:defifun ("__claw__ZNK2aw8filament13InMemoryInput7getNameEv"
               %filament.util::aw+filament+get-name :non-mutating t)
              claw-utils:claw-string
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:94:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-input)))

(iffi:defitype %filament.util::ssize-t
               :int
               "/usr/x86_64-w64-mingw32/include/corecrt.h:47:13")

(iffi:defifun ("__claw__ZN2aw8filament13InMemoryInput4openEv"
               %filament.util::aw+filament+open)
              %filament.util::ssize-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:79:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-input)))

(iffi:defifun ("__claw__ZN2aw8filament13InMemoryInputD1Ev"
               %filament.util::aw+filament+~in-memory-input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:77:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-input)))

(iffi:deficlass (%filament.util::aw+filament+in-memory-output
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament14InMemoryOutputC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament14InMemoryOutputC2Ev"
                 :constructor
                 %filament.util::aw+filament+in-memory-output
                 :destructor
                 %filament.util::aw+filament+~in-memory-output)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:38:7")

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutputC1Ev"
               %filament.util::aw+filament+in-memory-output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:40:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutput5closeEv"
               %filament.util::aw+filament+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:62:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output)))

(iffi:deficlass (%filament.util::aw+filament+material-data
                 :size-reporter
                 "__claw_sizeof__ZN2aw8filament12MaterialDataC2EPvj"
                 :alignment-reporter
                 "__claw_alignof__ZN2aw8filament12MaterialDataC2EPvj"
                 :constructor
                 %filament.util::aw+filament+material-data
                 :destructor
                 %filament.util::aw+filament+~material-data)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:12:7")

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutput12materialDataEv"
               %filament.util::aw+filament+material-data)
              (claw-utils:claw-pointer
               %filament.util::aw+filament+material-data)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:58:19"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutput4openEv"
               %filament.util::aw+filament+open)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:45:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutput5writeEPKhj"
               %filament.util::aw+filament+write)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:49:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament14InMemoryOutputD1Ev"
               %filament.util::aw+filament+~in-memory-output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:43:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+in-memory-output)))

(iffi:defifun ("__claw__ZN2aw8filament12MaterialDataC1EPvj"
               %filament.util::aw+filament+material-data)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:14:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+material-data))
              (%filament.util::data (claw-utils:claw-pointer :void))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN2aw8filament12MaterialData4dataEv"
               %filament.util::aw+filament+data)
              (claw-utils:claw-pointer :void)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:29:11"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+material-data)))

(iffi:defifun ("__claw__ZN2aw8filament12MaterialData4sizeEv"
               %filament.util::aw+filament+size)
              %filament.util::size-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:25:12"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+material-data)))

(iffi:defifun ("__claw__ZN2aw8filament12MaterialDataD1Ev"
               %filament.util::aw+filament+~material-data)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/ClawMemIo.h:21:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::aw+filament+material-data)))

(iffi:deficlass (%filament.util::filamat+material-builder
                 :size-reporter
                 "__claw_sizeof__ZN7filamat15MaterialBuilderC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN7filamat15MaterialBuilderC2Ev"
                 :constructor
                 %filament.util::filamat+material-builder :destructor
                 %filament.util::filamat+~material-builder)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:176:20")

(cffi:defcenum (%filament.util::filamat+material-builder+output-target
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:214:16"
               (:color 0)
               (:depth 1))

(cffi:defcenum (%filament.util::filamat+material-builder+output-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:219:16"
               (:float 0)
               (:float2 1)
               (:float3 2)
               (:float4 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:181:16"
               (:custom0 0)
               (:custom1 1)
               (:custom2 2)
               (:custom3 3))

(cffi:defcenum (%filament.util::filamat+material-builder+variable-qualifier
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:210:16"
               (:out 0))

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilderC1Ev"
               %filament.util::filamat+material-builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:178:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(cffi:defcenum (%filament.util::backend+precision
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:231:12"
               (:low 0)
               (:medium 1)
               (:high 2)
               (:default 3))

(iffi:defitype %filament.util::filamat+material-builder+parameter-precision
               %filament.util::backend+precision
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:207:11")

(iffi:defistruct (%filament.util::filamat+material-builder+parameter
                  :size-reporter
                  "__claw_sizeof_filamatWMaterialBuilderWParameter"
                  :alignment-reporter
                  "__claw_alignof_filamatWMaterialBuilderWParameter"
                  :constructor %filament.util::filamat+parameter)
                 nil
                 "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:561:12")

(defparameter %filament.util::+invalid+ 0)

(defparameter %filament.util::+uniform+ 1)

(defparameter %filament.util::+sampler+ 2)

(defparameter %filament.util::+subpass+ 3)

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1Ev"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:562:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter)))

(cffi:defcenum (%filament.util::backend+sampler-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:239:12"
               (:2d 0)
               (:2d-array 1)
               (:cubemap 2)
               (:external 3)
               (:3d 4)
               (:cubemap-array 5))

(iffi:defitype %filament.util::filamat+material-builder+sampler-type
               %filament.util::backend+sampler-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:204:11")

(cffi:defcenum (%filament.util::backend+sampler-format
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:254:12"
               (:int 0)
               (:uint 1)
               (:float 2)
               (:shadow 3))

(iffi:defitype %filament.util::filamat+material-builder+sampler-format
               %filament.util::backend+sampler-format
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:206:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SamplerTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:565:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+sampler-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+subpass-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:249:12"
               (:subpass-input 0))

(iffi:defitype %filament.util::filamat+material-builder+subpass-type
               %filament.util::backend+subpass-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:205:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11SubpassTypeENS5_13SamplerFormatENS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:573:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+subpass-type)
              (%filament.util::f
               %filament.util::filamat+material-builder+sampler-format)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(cffi:defcenum (%filament.util::backend+uniform-type
                %filament.util::uint8-t)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/filament/backend/include/backend/DriverEnums.h:209:12"
               (:bool 0)
               (:bool2 1)
               (:bool3 2)
               (:bool4 3)
               (:float 4)
               (:float2 5)
               (:float3 6)
               (:float4 7)
               (:int 8)
               (:int2 9)
               (:int3 10)
               (:int4 11)
               (:uint 12)
               (:uint2 13)
               (:uint3 14)
               (:uint4 15)
               (:mat3 16)
               (:mat4 17)
               (:struct 18))

(iffi:defitype %filament.util::filamat+material-builder+uniform-type
               %filament.util::backend+uniform-type
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:203:11")

(iffi:defifun ("__claw__ZN7filamat15MaterialBuilder9ParameterC1EPKcN8filament7backend11UniformTypeEjNS5_9PrecisionE"
               %filament.util::filamat+parameter)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:569:9"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder+parameter))
              (%filament.util::param-name claw-utils:claw-string)
              (%filament.util::t
               %filament.util::filamat+material-builder+uniform-type)
              (%filament.util::type-size %filament.util::size-t)
              (%filament.util::p
               %filament.util::filamat+material-builder+parameter-precision))

(iffi:deficlass (%filament.util::filamat+material-builder-base
                 :size-reporter
                 "__claw_sizeof_filamatWMaterialBuilderBase"
                 :alignment-reporter
                 "__claw_alignof_filamatWMaterialBuilderBase")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:51:20")

(cffi:defcenum (%filament.util::filamat+material-builder-base+optimization
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:75:16"
               (:none 0)
               (:preprocessor 1)
               (:size 2)
               (:performance 3))

(cffi:defcenum (%filament.util::filamat+material-builder-base+target-language
                :int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:70:16"
               (:glsl 0)
               (:spirv 1))

(iffi:defifun ("__claw_cE3AE40NE40filamatE40SE40MaterialBuilder_claw_dtor"
               %filament.util::filamat+~material-builder)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filamat/include/filamat/MaterialBuilder.h:176:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::filamat+material-builder)))

(iffi:defitype %filament.util::user-variant-filter-mask
               :unsigned-int
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/filabridge/include/filament/MaterialEnums.h:244:7")

(cffi:defcenum (%filament.util::matc+material-type :unsigned-int)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:24:6"
               (:block 0)
               (:identifier 1)
               (:unknown 2))

(iffi:deficlass (%filament.util::matc+compiler :size-reporter
                 "__claw_sizeof_matcWCompiler" :alignment-reporter
                 "__claw_alignof_matcWCompiler" :destructor
                 %filament.util::matc+~compiler)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:26:7")

(iffi:defifun ("__claw__ZN4matc8CompilerD1Ev"
               %filament.util::matc+~compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Compiler.h:28:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+compiler)))

(iffi:deficlass (%filament.util::matc+config :size-reporter
                 "__claw_sizeof_matcWConfig" :alignment-reporter
                 "__claw_alignof_matcWConfig" :destructor
                 %filament.util::matc+~config)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:33:7")

(iffi:defifun ("__claw__ZNK4matc6Config8getInputEv"
               %filament.util::matc+get-input :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+input)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:74:20"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defitype %filament.util::matc+config+optimization
               %filament.util::filamat+material-builder-base+optimization
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:42:11")

(iffi:defifun ("__claw__ZNK4matc6Config20getOptimizationLevelEv"
               %filament.util::matc+get-optimization-level
               :non-mutating t)
              %filament.util::matc+config+optimization
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:94:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config9getOutputEv"
               %filament.util::matc+get-output :non-mutating t)
              (claw-utils:claw-pointer
               %filament.util::matc+config+output)
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:64:21"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config15getOutputFormatEv"
               %filament.util::matc+get-output-format :non-mutating
               t)
              %filament.util::matc+config+output-format
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:86:18"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config11getPlatformEv"
               %filament.util::matc+get-platform :non-mutating t)
              %filament.util::matc+config+platform
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:82:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config19getReflectionTargetEv"
               %filament.util::matc+get-reflection-target
               :non-mutating t)
              %filament.util::matc+config+metadata
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:102:14"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config12getTargetApiEv"
               %filament.util::matc+get-target-api :non-mutating t)
              %filament.util::matc+config+target-api
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:106:15"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config16getVariantFilterEv"
               %filament.util::matc+get-variant-filter :non-mutating
               t)
              %filament.util::user-variant-filter-mask
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:118:37"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config7isDebugEv"
               %filament.util::matc+is-debug :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:78:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config7isValidEv"
               %filament.util::matc+is-valid :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:90:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config12printShadersEv"
               %filament.util::matc+print-shaders :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:110:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZNK4matc6Config13rawShaderModeEv"
               %filament.util::matc+raw-shader-mode :non-mutating t)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:114:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc6Config20setOptimizationLevelEN7filamat19MaterialBuilderBase12OptimizationE"
               %filament.util::matc+set-optimization-level)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:98:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config))
              (%filament.util::level
               %filament.util::matc+config+optimization))

(iffi:defifun ("__claw__ZN4matc6ConfigD1Ev"
               %filament.util::matc+~config)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:54:13"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc6Config5Input5closeEv"
               %filament.util::matc+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:71:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZNK4matc6Config5Input7getNameEv"
               %filament.util::matc+get-name :non-mutating t)
              claw-utils:claw-string
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:72:29"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config5Input4openEv"
               %filament.util::matc+open)
              %filament.util::ssize-t
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:69:25"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config5InputD1Ev"
               %filament.util::matc+~input)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:68:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+input)))

(iffi:defifun ("__claw__ZN4matc6Config6Output5closeEv"
               %filament.util::matc+close)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:62:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:defifun ("__claw__ZN4matc6Config6Output4openEv"
               %filament.util::matc+open)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:59:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:defifun ("__claw__ZN4matc6Config6Output5writeEPKhj"
               %filament.util::matc+write)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:60:22"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output))
              (%filament.util::data
               (claw-utils:claw-pointer %filament.util::uint8-t))
              (%filament.util::size %filament.util::size-t))

(iffi:defifun ("__claw__ZN4matc6Config6OutputD1Ev"
               %filament.util::matc+~output)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Config.h:58:17"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+config+output)))

(iffi:deficlass (%filament.util::matc+jsonish-value :size-reporter
                 nil :alignment-reporter nil)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:33:7")

(iffi:deficlass (%filament.util::matc+lexeme<matc+material-type>
                 :size-reporter
                 "__claw_sizeof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc6LexemeINS_12MaterialTypeEEC2ES1_PKcS4_jj")
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/Lexeme.h:28:7")

(iffi:deficlass (%filament.util::matc+material-compiler
                 :size-reporter
                 "__claw_sizeof__ZN4matc16MaterialCompilerC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc16MaterialCompilerC2Ev"
                 :constructor %filament.util::matc+material-compiler
                 :destructor %filament.util::matc+~material-compiler)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7")

(iffi:defifun ("__claw__ZN4matc16MaterialCompilerC1Ev"
               %filament.util::matc+material-compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:36:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler15checkParametersERKNS_6ConfigE"
               %filament.util::matc+check-parameters)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:40:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defifun ("__claw__ZN4matc16MaterialCompiler3runERKNS_6ConfigE"
               %filament.util::matc+run)
              :bool
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:38:10"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler))
              (%filament.util::config
               (claw-utils:claw-pointer %filament.util::matc+config)))

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:71:11")

(iffi:defitype %filament.util::matc+material-compiler+material-config-processor-json
               (claw-utils:claw-pointer :void)
               "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:77:11")

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialCompiler_claw_dtor"
               %filament.util::matc+~material-compiler)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialCompiler.h:34:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-compiler)))

(iffi:deficlass (%filament.util::matc+material-lexeme :size-reporter
                 "__claw_sizeof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj"
                 :alignment-reporter
                 "__claw_alignof__ZN4matc14MaterialLexemeC2ENS_12MaterialTypeEPKcS3_jj"
                 :constructor %filament.util::matc+material-lexeme
                 :destructor %filament.util::matc+~material-lexeme)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7")

(iffi:defifun ("__claw__ZN4matc14MaterialLexemeC1ENS_12MaterialTypeEPKcS3_jj"
               %filament.util::matc+material-lexeme)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:32:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme))
              (%filament.util::type
               %filament.util::matc+material-type)
              (%filament.util::start claw-utils:claw-string)
              (%filament.util::end claw-utils:claw-string)
              (%filament.util::line %filament.util::size-t)
              (%filament.util::pos %filament.util::size-t))

(iffi:defifun ("__claw_cE3AE40NE40matcE40SE40MaterialLexeme_claw_dtor"
               %filament.util::matc+~material-lexeme)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/tools/matc/src/matc/MaterialLexeme.h:30:7"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::matc+material-lexeme)))

(iffi:deficlass (%filament.util::utils+bitset<unsigned+int+1+void>
                 :size-reporter
                 "__claw_sizeof__ZN5utils6bitsetIjLj1EvEC2Ev"
                 :alignment-reporter
                 "__claw_alignof__ZN5utils6bitsetIjLj1EvEC2Ev"
                 :constructor
                 %filament.util::utils+bitset<unsigned+int+1+void>)
                nil
                "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/utils/include/utils/bitset.h:49:20")

(iffi:defifun ("__claw__ZN5utils6bitsetIjLj1EvEC1Ev"
               %filament.util::utils+bitset<unsigned+int+1+void>)
              :void
              "/home/borodust/devel/repo/awie-projects/aw-filament/src/lib/filament/libs/utils/include/utils/bitset.h:58:5"
              (%filament.util::%%claw-this-
               (claw-utils:claw-pointer
                %filament.util::utils+bitset<unsigned+int+1+void>)))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%filament.util::filamat+material-builder+output-target
          :%filament.util)
  (export '%filament.util::aw+filament+open :%filament.util)
  (export '%filament.util::matc+run :%filament.util)
  (export '%filament.util::+sampler+ :%filament.util)
  (export '%filament.util::aw+filament+data :%filament.util)
  (export '%filament.util::+invalid+ :%filament.util)
  (export '%filament.util::aw+filament+util+resize-file
          :%filament.util)
  (export '%filament.util::matc+config+input :%filament.util)
  (export '%filament.util::filamat+parameter :%filament.util)
  (export '%filament.util::filamat+material-builder :%filament.util)
  (export '%filament.util::matc+write :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor
          :%filament.util)
  (export '%filament.util::aw+filament+get-name :%filament.util)
  (export '%filament.util::filamat+material-builder+variable-qualifier
          :%filament.util)
  (export '%filament.util::aw+filament+get-input :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-type
          :%filament.util)
  (export '%filament.util::matc+material-compiler :%filament.util)
  (export '%filament.util::matc+close :%filament.util)
  (export '%filament.util::+uniform+ :%filament.util)
  (export '%filament.util::matc+is-valid :%filament.util)
  (export '%filament.util::matc+~config :%filament.util)
  (export '%filament.util::aw+filament+write :%filament.util)
  (export '%filament.util::aw+filament+set-raw-shader-mode
          :%filament.util)
  (export '%filament.util::matc+config+metadata :%filament.util)
  (export '%filament.util::matc+get-platform :%filament.util)
  (export '%filament.util::aw+filament+in-memory-output
          :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter
          :%filament.util)
  (export '%filament.util::matc+raw-shader-mode :%filament.util)
  (export '%filament.util::filamat+material-builder+parameter-precision
          :%filament.util)
  (export '%filament.util::matc+material-compiler+material-config-processor-json
          :%filament.util)
  (export '%filament.util::matc+set-optimization-level
          :%filament.util)
  (export '%filament.util::aw+filament+close :%filament.util)
  (export '%filament.util::filamat+material-builder+variable
          :%filament.util)
  (export '%filament.util::matc+config+target-api :%filament.util)
  (export '%filament.util::filamat+material-builder+output-type
          :%filament.util)
  (export '%filament.util::matc+~material-compiler :%filament.util)
  (export '%filament.util::aw+filament+set-reflection-target
          :%filament.util)
  (export '%filament.util::matc+~input :%filament.util)
  (export '%filament.util::backend+sampler-format :%filament.util)
  (export '%filament.util::matc+print-shaders :%filament.util)
  (export '%filament.util::matc+get-optimization-level
          :%filament.util)
  (export '%filament.util::user-variant-filter-mask :%filament.util)
  (export '%filament.util::matc+~compiler :%filament.util)
  (export '%filament.util::matc+compiler :%filament.util)
  (export '%filament.util::matc+~material-lexeme :%filament.util)
  (export '%filament.util::aw+filament+set-variant-filter
          :%filament.util)
  (export '%filament.util::filamat+material-builder-base+optimization
          :%filament.util)
  (export '%filament.util::matc+get-input :%filament.util)
  (export '%filament.util::matc+config+optimization :%filament.util)
  (export '%filament.util::aw+filament+set-platform :%filament.util)
  (export '%filament.util::aw+filament+is-print-shaders
          :%filament.util)
  (export '%filament.util::filamat+material-builder+sampler-format
          :%filament.util)
  (export '%filament.util::backend+sampler-type :%filament.util)
  (export '%filament.util::matc+material-lexeme :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-language
          :%filament.util)
  (export '%filament.util::ssize-t :%filament.util)
  (export '%filament.util::matc+config+platform :%filament.util)
  (export '%filament.util::aw+filament+~material-data
          :%filament.util)
  (export '%filament.util::filamat+material-builder-base+target-api
          :%filament.util)
  (export '%filament.util::aw+filament+~in-memory-input
          :%filament.util)
  (export '%filament.util::filamat+material-builder+subpass-type
          :%filament.util)
  (export '%filament.util::aw+filament+set-debug :%filament.util)
  (export '%filament.util::matc+config+output-format :%filament.util)
  (export '%filament.util::matc+config :%filament.util)
  (export '%filament.util::backend+precision :%filament.util)
  (export '%filament.util::matc+is-debug :%filament.util)
  (export '%filament.util::aw+filament+set-target-api
          :%filament.util)
  (export '%filament.util::aw+filament+~in-memory-output
          :%filament.util)
  (export '%filament.util::matc+get-reflection-target
          :%filament.util)
  (export '%filament.util::filamat+~material-builder :%filament.util)
  (export '%filament.util::matc+lexeme<matc+material-type>
          :%filament.util)
  (export '%filament.util::aw+filament+in-memory-config
          :%filament.util)
  (export '%filament.util::aw+filament+in-memory-input
          :%filament.util)
  (export '%filament.util::uint8-t :%filament.util)
  (export '%filament.util::aw+filament+size :%filament.util)
  (export '%filament.util::backend+uniform-type :%filament.util)
  (export '%filament.util::matc+get-target-api :%filament.util)
  (export '%filament.util::filamat+material-builder+uniform-type
          :%filament.util)
  (export '%filament.util::matc+check-parameters :%filament.util)
  (export '%filament.util::filamat+material-builder-base
          :%filament.util)
  (export '%filament.util::aw+filament+set-output-format
          :%filament.util)
  (export '%filament.util::matc+get-variant-filter :%filament.util)
  (export '%filament.util::matc+jsonish-value :%filament.util)
  (export '%filament.util::filamat+material-builder-base+platform
          :%filament.util)
  (export '%filament.util::matc+get-output :%filament.util)
  (export '%filament.util::matc+~output :%filament.util)
  (export '%filament.util::aw+filament+~in-memory-config
          :%filament.util)
  (export '%filament.util::aw+filament+material-data :%filament.util)
  (export '%filament.util::matc+get-name :%filament.util)
  (export '%filament.util::utils+bitset<unsigned+int+1+void>
          :%filament.util)
  (export '%filament.util::matc+material-type :%filament.util)
  (export '%filament.util::aw+filament+set-print-shaders
          :%filament.util)
  (export '%filament.util::matc+config+output :%filament.util)
  (export '%filament.util::+subpass+ :%filament.util)
  (export '%filament.util::aw+filament+get-output :%filament.util)
  (export '%filament.util::matc+get-output-format :%filament.util)
  (export '%filament.util::size-t :%filament.util)
  (export '%filament.util::matc+open :%filament.util)
  (export '%filament.util::backend+subpass-type :%filament.util))

